import type { NewExercise } from './types'

export const BACK_EXERCISES: NewExercise[] = [
  {
    id: 'pull-up', slug: 'pull-up',
    nameEn: 'Pull-Up', nameIt: 'Trazioni alla Sbarra',
    descriptionEn: 'The upper body squat. Builds lat width, biceps, and overall back thickness.',
    descriptionIt: 'Lo squat della parte superiore del corpo. Sviluppa i dorsali, i bicipiti e lo spessore della schiena.',
    primaryMuscles: JSON.stringify(['lats']),
    secondaryMuscles: JSON.stringify(['biceps', 'upper_back', 'rear_delts']),
    equipmentId: 'pullup_bar', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hang from bar with overhand grip','Pull chest toward bar','Squeeze lats at top','Lower with control to full hang','Repeat']),
    instructionsIt: JSON.stringify(['Appenditi alla sbarra con presa prona','Tira il petto verso la sbarra','Contrai i dorsali in alto','Scendi con controllo fino all\'allungamento completo','Ripeti']),
    mistakesEn: JSON.stringify(['Kipping/swinging body','Not reaching full extension','Chin barely over bar','Shrugging shoulders up']),
    mistakesIt: JSON.stringify(['Oscillare il corpo','Non raggiungere l\'estensione completa','Mento appena sopra la sbarra','Alzare le spalle']),
    tipsEn: JSON.stringify(['Depress scapulae before pulling','Lead with elbows, not hands','Hollow body position','Progress with band assistance']),
    tipsIt: JSON.stringify(['Abbassa le scapole prima di tirare','Guida con i gomiti, non con le mani','Posizione hollow body','Progredisci con elastico di assistenza']),
    breathingEn: 'Exhale on the way up, inhale on descent.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['lat-pulldown', 'assisted-pull-up', 'inverted-row']),
    tags: JSON.stringify(['compound','back','pull','bodyweight','strength']),
  },
  {
    id: 'chin-up', slug: 'chin-up',
    nameEn: 'Chin-Up', nameIt: 'Trazioni Supine',
    descriptionEn: 'Supinated grip pull-up that emphasizes biceps and lower lats more than standard pull-ups.',
    descriptionIt: 'Trazioni con presa supina che enfatizzano i bicipiti e i dorsali bassi rispetto alle trazioni standard.',
    primaryMuscles: JSON.stringify(['lats']),
    secondaryMuscles: JSON.stringify(['biceps', 'upper_back']),
    equipmentId: 'pullup_bar', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hang with underhand (supinated) grip','Pull chin over bar','Full range of motion','Lower with control']),
    instructionsIt: JSON.stringify(['Appenditi con presa supina','Tira il mento sopra la sbarra','Ampiezza completa del movimento','Scendi con controllo']),
    mistakesEn: JSON.stringify(['Incomplete range','Elbows flaring wide','Using momentum']),
    mistakesIt: JSON.stringify(['Range incompleto','Gomiti troppo aperti','Usare slancio']),
    tipsEn: JSON.stringify(['Shoulder-width grip','Elbows close to body','Easier than pull-ups for most']),
    tipsIt: JSON.stringify(['Presa alla larghezza delle spalle','Gomiti vicini al corpo','Più facile delle trazioni prone per la maggior parte']),
    breathingEn: 'Exhale up, inhale down.',
    breathingIt: 'Espira su, inspira giù.',
    alternatives: JSON.stringify(['pull-up', 'lat-pulldown', 'cable-row']),
    tags: JSON.stringify(['compound','back','biceps','bodyweight']),
  },
  {
    id: 'lat-pulldown', slug: 'lat-pulldown',
    nameEn: 'Lat Pulldown', nameIt: 'Lat Machine',
    descriptionEn: 'Cable machine pull-down to train lat width. Great for beginners and high volume work.',
    descriptionIt: 'Tirata alla lat machine per sviluppare la larghezza dei dorsali. Ottima per principianti e lavoro ad alto volume.',
    primaryMuscles: JSON.stringify(['lats']),
    secondaryMuscles: JSON.stringify(['biceps', 'upper_back', 'rear_delts']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Sit with thighs locked under pads','Wide overhand grip on bar','Pull bar to upper chest','Control return to full extension']),
    instructionsIt: JSON.stringify(['Siediti con le cosce bloccate sotto i cuscinetti','Presa larga prona sulla barra','Tira la barra al petto alto','Controlla il ritorno all\'estensione completa']),
    mistakesEn: JSON.stringify(['Pulling behind neck','Leaning back too much','Not fully extending arms at top','Jerking weight']),
    mistakesIt: JSON.stringify(['Tirare dietro al collo','Inclinarsi troppo all\'indietro','Non estendere completamente le braccia','Strappare il peso']),
    tipsEn: JSON.stringify(['Slight backward lean (15-20°)','Elbows point down and back','Squeeze lats at bottom']),
    tipsIt: JSON.stringify(['Leggera inclinazione all\'indietro (15-20°)','I gomiti puntano in basso e indietro','Contrai i dorsali in basso']),
    breathingEn: 'Exhale on pull, inhale on return.',
    breathingIt: 'Espira nella trazione, inspira nel ritorno.',
    alternatives: JSON.stringify(['pull-up', 'cable-straight-arm-pulldown', 'single-arm-lat-pulldown']),
    tags: JSON.stringify(['compound','back','cable','lat']),
  },
  {
    id: 'barbell-row', slug: 'barbell-row',
    nameEn: 'Barbell Row', nameIt: 'Rematore con Bilanciere',
    descriptionEn: 'Bent-over barbell row. One of the best mass builders for the entire back.',
    descriptionIt: 'Rematore con busto inclinato. Uno dei migliori esercizi per la massa di tutta la schiena.',
    primaryMuscles: JSON.stringify(['lats', 'upper_back']),
    secondaryMuscles: JSON.stringify(['biceps', 'rear_delts', 'lower_back']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hip hinge to ~45° torso angle','Overhand grip, slightly wider than shoulder','Pull bar to lower chest/navel','Squeeze back at top','Lower with control']),
    instructionsIt: JSON.stringify(['Hip hinge con busto a ~45°','Presa prona, leggermente più larga delle spalle','Tira la barra al basso petto/ombelico','Contrai la schiena in alto','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Rounding lower back','Using too much leg drive','Pulling to wrong point','Standing too upright']),
    mistakesIt: JSON.stringify(['Inarcare la schiena bassa','Usare troppa spinta delle gambe','Tirare nel punto sbagliato','Stare troppo eretti']),
    tipsEn: JSON.stringify(['Neutral spine throughout','Retract scapulae at top','Braced core','Elbows ~45° from torso']),
    tipsIt: JSON.stringify(['Colonna neutra per tutto il movimento','Retrai le scapole in alto','Core in tensione','Gomiti a ~45° dal busto']),
    breathingEn: 'Inhale at bottom, exhale on pull.',
    breathingIt: 'Inspira in basso, espira nella trazione.',
    alternatives: JSON.stringify(['dumbbell-row', 'cable-row', 'machine-row']),
    tags: JSON.stringify(['compound','back','pull','strength','barbell']),
  },
  {
    id: 'dumbbell-row', slug: 'dumbbell-row',
    nameEn: 'Single-Arm Dumbbell Row', nameIt: 'Rematore con Manubrio',
    descriptionEn: 'Unilateral back exercise that allows full range of motion and corrects imbalances.',
    descriptionIt: 'Esercizio unilaterale per la schiena che consente piena escursione e corregge squilibri.',
    primaryMuscles: JSON.stringify(['lats', 'upper_back']),
    secondaryMuscles: JSON.stringify(['biceps', 'rear_delts']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Place hand and knee on bench','Hold dumbbell in free hand','Pull elbow back and up','Squeeze lat at top','Lower with control']),
    instructionsIt: JSON.stringify(['Appoggia mano e ginocchio sulla panca','Tieni il manubrio nella mano libera','Tira il gomito indietro e in alto','Contrai il dorsale in alto','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Rotating torso excessively','Pulling with arm not back','Shrugging at top']),
    mistakesIt: JSON.stringify(['Rotare il busto eccessivamente','Tirare col braccio anziché la schiena','Alzare le spalle in alto']),
    tipsEn: JSON.stringify(['Think "elbow to hip"','Keep shoulder depressed','Full stretch at bottom']),
    tipsIt: JSON.stringify(['Pensa "gomito verso il fianco"','Mantieni la spalla abbassata','Allungamento completo in basso']),
    breathingEn: 'Exhale on pull, inhale on return.',
    breathingIt: 'Espira nella trazione, inspira nel ritorno.',
    alternatives: JSON.stringify(['barbell-row', 'cable-row', 'machine-row']),
    tags: JSON.stringify(['compound','back','unilateral','dumbbell']),
  },
  {
    id: 'cable-row', slug: 'cable-row',
    nameEn: 'Seated Cable Row', nameIt: 'Rematore ai Cavi Seduto',
    descriptionEn: 'Constant tension cable rowing for mid-back thickness and lat development.',
    descriptionIt: 'Rematore ai cavi con tensione costante per lo spessore del dorso medio e lo sviluppo dei dorsali.',
    primaryMuscles: JSON.stringify(['lats', 'upper_back']),
    secondaryMuscles: JSON.stringify(['biceps', 'rear_delts']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Sit with feet on footrest','Slight forward lean at start','Pull handle to abdomen','Drive elbows back','Control return to stretch']),
    instructionsIt: JSON.stringify(['Siediti con i piedi sul supporto','Leggera inclinazione in avanti all\'inizio','Tira il manubrio verso l\'addome','Spinge i gomiti indietro','Controlla il ritorno all\'allungamento']),
    mistakesEn: JSON.stringify(['Excessive torso swing','Incomplete range of motion','Shrugging at end position']),
    mistakesIt: JSON.stringify(['Oscillazione eccessiva del busto','Range di movimento incompleto','Alzare le spalle nella posizione finale']),
    tipsEn: JSON.stringify(['Maintain upright torso','Retract and depress scapulae','Squeeze at full contraction']),
    tipsIt: JSON.stringify(['Mantieni il busto eretto','Retrarre e abbassare le scapole','Contrai alla massima contrazione']),
    breathingEn: 'Exhale on pull, inhale on return.',
    breathingIt: 'Espira nella trazione, inspira nel ritorno.',
    alternatives: JSON.stringify(['barbell-row', 'dumbbell-row', 'machine-row']),
    tags: JSON.stringify(['compound','back','cable','hypertrophy']),
  },
  {
    id: 'deadlift', slug: 'deadlift',
    nameEn: 'Deadlift', nameIt: 'Stacco da Terra',
    descriptionEn: 'The king of compound exercises. Builds total body strength with emphasis on posterior chain.',
    descriptionIt: 'Il re degli esercizi composti. Costruisce la forza di tutto il corpo con enfasi sulla catena posteriore.',
    primaryMuscles: JSON.stringify(['lower_back', 'glutes', 'hamstrings']),
    secondaryMuscles: JSON.stringify(['lats', 'traps', 'quads', 'forearms']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Stand with feet hip-width, bar over mid-foot','Hinge and grip bar shoulder-width','Chest up, neutral spine','Drive floor away, keep bar close','Lock out hips and knees at top']),
    instructionsIt: JSON.stringify(['In piedi con i piedi alla larghezza delle anche, barra sopra il metatarso','Hip hinge e impugna la barra alla larghezza delle spalle','Petto alto, colonna neutra','Spingi il pavimento lontano, tieni la barra vicina','Blocca anche e ginocchia in alto']),
    mistakesEn: JSON.stringify(['Rounding lower back','Bar drifting from body','Looking up excessively','Jerking the bar']),
    mistakesIt: JSON.stringify(['Curvare la schiena bassa','La barra si allontana dal corpo','Guardare in alto eccessivamente','Strappare la barra']),
    tipsEn: JSON.stringify(['Push the floor away (not lift the bar)','Lat engagement protects spine','Hip hinge not squat pattern','Brace 360° around core']),
    tipsIt: JSON.stringify(['Spingi il pavimento lontano (non sollevare la barra)','Attivare i dorsali protegge la colonna','Pattern hip hinge non squat','Mantieni tensione 360° intorno al core']),
    breathingEn: 'Valsalva breath: big inhale, hold through rep, exhale at top.',
    breathingIt: 'Manovra di Valsalva: grande inspirazione, trattieni durante la rep, espira in alto.',
    alternatives: JSON.stringify(['romanian-deadlift', 'sumo-deadlift', 'trap-bar-deadlift']),
    tags: JSON.stringify(['compound','back','hinge','strength','posterior-chain']),
  },
  {
    id: 'romanian-deadlift', slug: 'romanian-deadlift',
    nameEn: 'Romanian Deadlift', nameIt: 'Stacco Rumeno',
    descriptionEn: 'Hip hinge with emphasis on hamstring stretch. Excellent for posterior chain hypertrophy.',
    descriptionIt: 'Hip hinge con enfasi sull\'allungamento dei femorali. Eccellente per l\'ipertrofia della catena posteriore.',
    primaryMuscles: JSON.stringify(['hamstrings', 'glutes']),
    secondaryMuscles: JSON.stringify(['lower_back', 'lats']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Stand tall with barbell at hip level','Hinge at hips, pushing them back','Lower bar along legs to mid-shin','Feel hamstring stretch','Drive hips forward to return']),
    instructionsIt: JSON.stringify(['In piedi con il bilanciere all\'altezza dei fianchi','Hip hinge spingendo i fianchi indietro','Abbassa la barra lungo le gambe fino a metà tibia','Senti l\'allungamento dei femorali','Spingi i fianchi in avanti per tornare']),
    mistakesEn: JSON.stringify(['Bending knees too much (becomes deadlift)','Rounding back','Bar drifting away from body']),
    mistakesIt: JSON.stringify(['Piegare troppo le ginocchia (diventa stacco)','Curvare la schiena','La barra si allontana dal corpo']),
    tipsEn: JSON.stringify(['Soft knee bend only','Feel stretch before returning','Controlled eccentric (3-4s down)']),
    tipsIt: JSON.stringify(['Solo leggera flessione delle ginocchia','Senti l\'allungamento prima di tornare','Eccentrico controllato (3-4s in discesa)']),
    breathingEn: 'Inhale on descent, exhale on return.',
    breathingIt: 'Inspira in discesa, espira nel ritorno.',
    alternatives: JSON.stringify(['deadlift', 'good-morning', 'nordic-curl']),
    tags: JSON.stringify(['compound','hamstrings','hinge','posterior-chain']),
  },
  {
    id: 'face-pull', slug: 'face-pull',
    nameEn: 'Face Pull', nameIt: 'Face Pull',
    descriptionEn: 'Rear delt and upper back exercise essential for shoulder health and posture.',
    descriptionIt: 'Esercizio per i deltoidi posteriori e la schiena alta, essenziale per la salute delle spalle e la postura.',
    primaryMuscles: JSON.stringify(['rear_delts', 'upper_back']),
    secondaryMuscles: JSON.stringify(['traps', 'rotator_cuff']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set cable at face height with rope attachment','Step back and grab rope with both hands','Pull rope to face, spreading hands wide','External rotate at end of movement','Control return']),
    instructionsIt: JSON.stringify(['Imposta il cavo all\'altezza del viso con corda','Fai un passo indietro e afferra la corda con entrambe le mani','Tira la corda verso il viso allargando le mani','Ruota esternamente a fine movimento','Controlla il ritorno']),
    mistakesEn: JSON.stringify(['Pulling too heavy','Not externally rotating','Shrugging shoulders','Using torso momentum']),
    mistakesIt: JSON.stringify(['Carico eccessivo','Non ruotare esternamente','Alzare le spalle','Usare lo slancio del busto']),
    tipsEn: JSON.stringify(['Light to moderate weight','Focus on external rotation','Great for shoulder prehab/rehab','High rep (15-20) works well']),
    tipsIt: JSON.stringify(['Carico leggero o moderato','Focus sulla rotazione esterna','Ottimo per prevenzione/riabilitazione spalle','Funziona bene con rep alte (15-20)']),
    breathingEn: 'Exhale on pull, inhale on return.',
    breathingIt: 'Espira nella trazione, inspira nel ritorno.',
    alternatives: JSON.stringify(['band-pull-apart', 'reverse-fly', 'dumbbell-rear-delt-fly']),
    tags: JSON.stringify(['isolation','rear-delts','upper-back','shoulder-health']),
  },
  {
    id: 'cable-straight-arm-pulldown', slug: 'cable-straight-arm-pulldown',
    nameEn: 'Cable Straight-Arm Pulldown', nameIt: 'Pulldown a Braccia Tese',
    descriptionEn: 'Isolates the lats through a long range of motion with minimal bicep involvement.',
    descriptionIt: 'Isola i dorsali attraverso un ampio range di movimento con minimo coinvolgimento dei bicipiti.',
    primaryMuscles: JSON.stringify(['lats']),
    secondaryMuscles: JSON.stringify(['triceps', 'rear_delts']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set cable high with straight bar or rope','Stand back, arms straight at ~45°','Pull bar to thighs with straight arms','Squeeze lats at bottom','Return with control']),
    instructionsIt: JSON.stringify(['Imposta il cavo alto con barra dritta o corda','Stai indietro, braccia dritte a ~45°','Tira la barra alle cosce con braccia dritte','Contrai i dorsali in basso','Ritorna con controllo']),
    mistakesEn: JSON.stringify(['Bending elbows','Standing too close to cable','Not hinging at hips']),
    mistakesIt: JSON.stringify(['Piegare i gomiti','Stare troppo vicini al cavo','Non fare il hip hinge']),
    tipsEn: JSON.stringify(['Slight hip hinge for stability','Arms slightly bent (not locked) to protect elbows','Slow eccentric']),
    tipsIt: JSON.stringify(['Leggero hip hinge per stabilità','Braccia leggermente piegate (non bloccate) per proteggere i gomiti','Eccentrico lento']),
    breathingEn: 'Exhale on pulldown, inhale on return.',
    breathingIt: 'Espira nel pulldown, inspira nel ritorno.',
    alternatives: JSON.stringify(['lat-pulldown', 'pull-up', 'dumbbell-pullover']),
    tags: JSON.stringify(['isolation','lats','cable']),
  },
  {
    id: 'inverted-row', slug: 'inverted-row',
    nameEn: 'Inverted Row', nameIt: 'Rematore Invertito',
    descriptionEn: 'Bodyweight horizontal row. Builds upper back and is a great pull-up progression.',
    descriptionIt: 'Rematore orizzontale a corpo libero. Sviluppa la schiena alta ed è ottima progressione per le trazioni.',
    primaryMuscles: JSON.stringify(['upper_back', 'lats']),
    secondaryMuscles: JSON.stringify(['biceps', 'rear_delts']),
    equipmentId: 'pullup_bar', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set bar at waist height','Lie under bar, grab overhand grip','Body straight from head to heels','Pull chest to bar','Lower with control']),
    instructionsIt: JSON.stringify(['Imposta la sbarra all\'altezza dei fianchi','Sdraiati sotto la sbarra, presa prona','Corpo dritto dalla testa ai talloni','Tira il petto verso la sbarra','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Sagging hips','Partial range of motion','Pulling with arms not back']),
    mistakesIt: JSON.stringify(['Fianchi che cedono','Range parziale di movimento','Tirare con le braccia anziché la schiena']),
    tipsEn: JSON.stringify(['Harder by lowering bar','Easier by bending knees','Add weight vest for progression']),
    tipsIt: JSON.stringify(['Più difficile abbassando la sbarra','Più facile piegando le ginocchia','Aggiungi gilet zavorrato per progressione']),
    breathingEn: 'Exhale on pull, inhale on descent.',
    breathingIt: 'Espira nella trazione, inspira nella discesa.',
    alternatives: JSON.stringify(['pull-up', 'dumbbell-row', 'cable-row']),
    tags: JSON.stringify(['compound','back','bodyweight','beginner']),
  },
  {
    id: 'good-morning', slug: 'good-morning',
    nameEn: 'Good Morning', nameIt: 'Good Morning',
    descriptionEn: 'Hip hinge with barbell on back. Targets lower back, hamstrings and glutes.',
    descriptionIt: 'Hip hinge con bilanciere sulla schiena. Bersaglia schiena bassa, femorali e glutei.',
    primaryMuscles: JSON.stringify(['lower_back', 'hamstrings']),
    secondaryMuscles: JSON.stringify(['glutes', 'upper_back']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Bar on upper traps, feet hip-width','Slight knee bend','Hip hinge, push hips back','Keep back flat, lower to ~90°','Drive hips forward to stand']),
    instructionsIt: JSON.stringify(['Bilanciere sui trapezi alti, piedi alla larghezza delle anche','Leggera flessione delle ginocchia','Hip hinge, spingi i fianchi indietro','Mantieni la schiena piatta, abbassa a ~90°','Spingi i fianchi in avanti per alzarti']),
    mistakesEn: JSON.stringify(['Rounding back','Too heavy too soon','Going too low with flexion']),
    mistakesIt: JSON.stringify(['Curvare la schiena','Troppo carico troppo presto','Abbassarsi troppo']),
    tipsEn: JSON.stringify(['Start very light to learn pattern','Core braced at all times','Great for deadlift accessory work']),
    tipsIt: JSON.stringify(['Inizia molto leggero per imparare il pattern','Core sempre in tensione','Ottimo esercizio accessorio per lo stacco']),
    breathingEn: 'Inhale before hinging, exhale on return.',
    breathingIt: 'Inspira prima dell\'hip hinge, espira nel ritorno.',
    alternatives: JSON.stringify(['romanian-deadlift', 'back-extension', 'cable-pull-through']),
    tags: JSON.stringify(['compound','lower-back','hamstrings','hinge']),
  },
  {
    id: 'hyperextension', slug: 'hyperextension',
    nameEn: 'Back Extension / Hyperextension', nameIt: 'Estensione Lombare',
    descriptionEn: 'Isolation exercise for lower back and glutes using a hyperextension bench.',
    descriptionIt: 'Esercizio di isolamento per la schiena bassa e i glutei usando il panca per estensioni.',
    primaryMuscles: JSON.stringify(['lower_back', 'glutes']),
    secondaryMuscles: JSON.stringify(['hamstrings']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Position on hyperextension bench, hips at pad','Cross arms or hold weight at chest','Lower torso down slowly','Extend back to neutral/slightly past','Control throughout']),
    instructionsIt: JSON.stringify(['Posizionati sulla panca, fianchi al cuscinetto','Incrocia le braccia o tieni un peso al petto','Abbassa il busto lentamente','Estendi la schiena fino a neutro/leggermente oltre','Controllo per tutto il movimento']),
    mistakesEn: JSON.stringify(['Hyperextending too far','Using momentum','Rounding lower back']),
    mistakesIt: JSON.stringify(['Estendere troppo','Usare lo slancio','Curvare la schiena bassa']),
    tipsEn: JSON.stringify(['Add weight as strength increases','Glute focus: hips forward at top','Lower back focus: neutral spine']),
    tipsIt: JSON.stringify(['Aggiungi peso man mano che la forza aumenta','Focus glutei: fianchi in avanti in alto','Focus schiena bassa: colonna neutra']),
    breathingEn: 'Inhale going down, exhale coming up.',
    breathingIt: 'Inspira scendendo, espira salendo.',
    alternatives: JSON.stringify(['romanian-deadlift', 'good-morning', 'reverse-hyperextension']),
    tags: JSON.stringify(['isolation','lower-back','glutes']),
  },
]
