import type { NewExercise } from './types'

export const ARM_EXERCISES: NewExercise[] = [
  // BICEPS
  {
    id: 'barbell-curl', slug: 'barbell-curl',
    nameEn: 'Barbell Curl', nameIt: 'Curl con Bilanciere',
    descriptionEn: 'Classic bicep exercise. Allows heavy loading for maximum bicep mass development.',
    descriptionIt: 'Classico esercizio per i bicipiti. Permette carichi pesanti per il massimo sviluppo della massa.',
    primaryMuscles: JSON.stringify(['biceps']),
    secondaryMuscles: JSON.stringify(['forearms']),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Stand with barbell, shoulder-width underhand grip','Keep elbows fixed at sides','Curl bar to shoulder level','Squeeze biceps at top','Lower with control (3s)']),
    instructionsIt: JSON.stringify(['In piedi con bilanciere, presa supina alla larghezza delle spalle','Tieni i gomiti fissi ai fianchi','Arriccia la barra fino alle spalle','Contrai i bicipiti in alto','Abbassa con controllo (3s)']),
    mistakesEn: JSON.stringify(['Swinging body/using momentum','Elbows drifting forward','Partial range of motion','Gripping too wide or narrow']),
    mistakesIt: JSON.stringify(['Oscillare il corpo/usare slancio','Gomiti che si spostano in avanti','Range parziale di movimento','Presa troppo larga o stretta']),
    tipsEn: JSON.stringify(['Supinate wrist at top for peak contraction','EZ bar version easier on wrists','Slow eccentric (3s) for hypertrophy']),
    tipsIt: JSON.stringify(['Supina il polso in alto per la massima contrazione','La versione EZ bar è più leggera sui polsi','Eccentrico lento (3s) per l\'ipertrofia']),
    breathingEn: 'Exhale on curl, inhale on descent.',
    breathingIt: 'Espira nel curl, inspira nella discesa.',
    alternatives: JSON.stringify(['dumbbell-curl', 'ez-bar-curl', 'cable-curl']),
    tags: JSON.stringify(['isolation','biceps','curl','barbell']),
  },
  {
    id: 'dumbbell-curl', slug: 'dumbbell-curl',
    nameEn: 'Dumbbell Curl', nameIt: 'Curl con Manubri',
    descriptionEn: 'Unilateral bicep curl with dumbbells. Allows supination for better peak contraction.',
    descriptionIt: 'Curl unilaterale per i bicipiti con manubri. Permette la supinazione per una migliore contrazione di picco.',
    primaryMuscles: JSON.stringify(['biceps']),
    secondaryMuscles: JSON.stringify(['forearms']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Stand or sit, dumbbell in each hand','Neutral grip at start','Curl, supinating wrist as you lift','Squeeze at top','Lower with control']),
    instructionsIt: JSON.stringify(['In piedi o seduto, un manubrio per mano','Presa neutra all\'inizio','Arriccia supinando il polso mentre sollevate','Contrai in alto','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Not supinating','Elbows drifting','Going too fast']),
    mistakesIt: JSON.stringify(['Non supinare','Gomiti che si spostano','Andare troppo veloce']),
    tipsEn: JSON.stringify(['Alternate or simultaneous','Concentration curl variation for isolation','Incline bench version stretches bicep more']),
    tipsIt: JSON.stringify(['Alternato o simultaneo','Il curl a concentrazione è una variante di isolamento','La versione su panca inclinata allunga di più il bicipite']),
    breathingEn: 'Exhale on curl, inhale on descent.',
    breathingIt: 'Espira nel curl, inspira nella discesa.',
    alternatives: JSON.stringify(['barbell-curl', 'cable-curl', 'hammer-curl']),
    tags: JSON.stringify(['isolation','biceps','curl','dumbbell']),
  },
  {
    id: 'hammer-curl', slug: 'hammer-curl',
    nameEn: 'Hammer Curl', nameIt: 'Curl Martello',
    descriptionEn: 'Neutral grip curl that targets brachialis and brachioradialis for arm thickness.',
    descriptionIt: 'Curl a presa neutra che bersaglia il brachiale e il brachioradiale per lo spessore del braccio.',
    primaryMuscles: JSON.stringify(['biceps']),
    secondaryMuscles: JSON.stringify(['forearms']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hold dumbbells with neutral grip (thumbs up)','Curl keeping palms facing each other','Do not rotate wrist','Full range of motion']),
    instructionsIt: JSON.stringify(['Tieni i manubri con presa neutra (pollici in su)','Arriccia mantenendo i palmi rivolti l\'uno all\'altro','Non ruotare il polso','Ampiezza completa del movimento']),
    mistakesEn: JSON.stringify(['Rotating to supinated grip','Elbow drift','Momentum']),
    mistakesIt: JSON.stringify(['Ruotare verso la presa supina','Deviazione del gomito','Slancio']),
    tipsEn: JSON.stringify(['Great for forearm and bicep thickness','Rope cable hammer curl is a variation','Alternating arms common']),
    tipsIt: JSON.stringify(['Ottimo per lo spessore dell\'avambraccio e del bicipite','Il curl martello con corda è una variante','Alternare le braccia è comune']),
    breathingEn: 'Exhale on curl, inhale on descent.',
    breathingIt: 'Espira nel curl, inspira nella discesa.',
    alternatives: JSON.stringify(['dumbbell-curl', 'barbell-curl', 'cable-curl']),
    tags: JSON.stringify(['isolation','biceps','forearms','curl']),
  },
  {
    id: 'preacher-curl', slug: 'preacher-curl',
    nameEn: 'Preacher Curl', nameIt: 'Curl al Banco Scott',
    descriptionEn: 'Arm-braced curl on a preacher bench. Eliminates momentum and isolates the bicep.',
    descriptionIt: 'Curl con il braccio appoggiato al banco scott. Elimina lo slancio e isola il bicipite.',
    primaryMuscles: JSON.stringify(['biceps']),
    secondaryMuscles: JSON.stringify(['forearms']),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Sit at preacher bench, rest arms on pad','Hold EZ bar or dumbbell','Curl to full contraction','Lower slowly to full extension']),
    instructionsIt: JSON.stringify(['Siediti al banco scott, appoggia le braccia sul cuscinetto','Tieni la barra EZ o il manubrio','Arriccia fino alla contrazione completa','Abbassa lentamente fino alla massima estensione']),
    mistakesEn: JSON.stringify(['Not reaching full extension at bottom','Going too heavy','Leaning into curl']),
    mistakesIt: JSON.stringify(['Non raggiungere la massima estensione in basso','Troppo carico','Inclinarsi nel curl']),
    tipsEn: JSON.stringify(['Full stretch at bottom is key','EZ bar easier on wrists','Good for beginner arm development']),
    tipsIt: JSON.stringify(['L\'allungamento completo in basso è fondamentale','La barra EZ è più leggera sui polsi','Ottima per lo sviluppo del braccio per principianti']),
    breathingEn: 'Exhale on curl, inhale on descent.',
    breathingIt: 'Espira nel curl, inspira nella discesa.',
    alternatives: JSON.stringify(['barbell-curl', 'dumbbell-curl', 'cable-curl']),
    tags: JSON.stringify(['isolation','biceps','preacher','curl']),
  },
  {
    id: 'cable-curl', slug: 'cable-curl',
    nameEn: 'Cable Curl', nameIt: 'Curl ai Cavi',
    descriptionEn: 'Constant tension bicep curl via cable machine. Excellent for pump and hypertrophy.',
    descriptionIt: 'Curl per i bicipiti a tensione costante tramite cavo. Eccellente per la congestione e l\'ipertrofia.',
    primaryMuscles: JSON.stringify(['biceps']),
    secondaryMuscles: JSON.stringify(['forearms']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set cable to low position','Grab straight bar or rope','Curl to shoulder height','Squeeze at top','Lower with control']),
    instructionsIt: JSON.stringify(['Imposta il cavo in posizione bassa','Prendi la barra dritta o la corda','Arriccia fino all\'altezza delle spalle','Contrai in alto','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Elbows drifting','Excessive torso movement','Not controlling return']),
    mistakesIt: JSON.stringify(['Gomiti che si spostano','Eccessivo movimento del busto','Non controllare il ritorno']),
    tipsEn: JSON.stringify(['Keep elbows pinned to sides','Cable provides tension even at full contraction','Rope gives neutral grip option']),
    tipsIt: JSON.stringify(['Tieni i gomiti fissi ai fianchi','Il cavo mantiene tensione anche alla massima contrazione','La corda offre opzione a presa neutra']),
    breathingEn: 'Exhale on curl, inhale on descent.',
    breathingIt: 'Espira nel curl, inspira nella discesa.',
    alternatives: JSON.stringify(['barbell-curl', 'dumbbell-curl', 'preacher-curl']),
    tags: JSON.stringify(['isolation','biceps','cable','curl']),
  },
  // TRICEPS
  {
    id: 'close-grip-bench', slug: 'close-grip-bench',
    nameEn: 'Close-Grip Bench Press', nameIt: 'Panca a Presa Stretta',
    descriptionEn: 'Compound tricep exercise using barbell. The best movement for tricep mass and strength.',
    descriptionIt: 'Esercizio composto per i tricipiti con bilanciere. Il miglior movimento per la massa e la forza dei tricipiti.',
    primaryMuscles: JSON.stringify(['triceps']),
    secondaryMuscles: JSON.stringify(['chest', 'front_delts']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Shoulder-width grip on barbell','Lower bar to lower chest','Elbows tucked at ~45°','Press up fully','Repeat']),
    instructionsIt: JSON.stringify(['Presa alla larghezza delle spalle sul bilanciere','Abbassa la barra al petto basso','Gomiti a ~45°','Spingi completamente','Ripeti']),
    mistakesEn: JSON.stringify(['Grip too narrow (wrist stress)','Elbows flaring out too wide','Partial range of motion']),
    mistakesIt: JSON.stringify(['Presa troppo stretta (stress sul polso)','Gomiti che si aprono troppo','Range di movimento parziale']),
    tipsEn: JSON.stringify(['Shoulder-width (not narrow) is correct','Elbows about 45° from torso','Good warm-up for heavy pressing']),
    tipsIt: JSON.stringify(['Alla larghezza delle spalle (non stretta) è corretto','Gomiti a circa 45° dal busto','Ottimo riscaldamento per la spinta pesante']),
    breathingEn: 'Exhale on press, inhale on descent.',
    breathingIt: 'Espira nella spinta, inspira nella discesa.',
    alternatives: JSON.stringify(['tricep-dips', 'skull-crusher', 'cable-pushdown']),
    tags: JSON.stringify(['compound','triceps','push','barbell','strength']),
  },
  {
    id: 'skull-crusher', slug: 'skull-crusher',
    nameEn: 'Skull Crusher', nameIt: 'French Press / Skull Crusher',
    descriptionEn: 'Lying tricep extension. Excellent for the long and medial head of the tricep.',
    descriptionIt: 'Estensione dei tricipiti da sdraiato. Eccellente per la testa lunga e mediale del tricipite.',
    primaryMuscles: JSON.stringify(['triceps']),
    secondaryMuscles: JSON.stringify([]),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Lie on bench, hold EZ bar above face','Lower bar toward forehead/overhead','Extend arms back to start','Control the eccentric']),
    instructionsIt: JSON.stringify(['Sdraiati sulla panca, tieni la barra EZ sopra il viso','Abbassa la barra verso la fronte/sopra la testa','Estendi le braccia al punto di partenza','Controlla l\'eccentrico']),
    mistakesEn: JSON.stringify(['Elbows flaring out','Moving elbows instead of just forearms','Going too heavy']),
    mistakesIt: JSON.stringify(['Gomiti che si aprono','Spostare i gomiti invece delle sole avambraccio','Troppo carico']),
    tipsEn: JSON.stringify(['EZ bar reduces wrist stress','Elbows should stay fixed pointing at ceiling','Can also do with dumbbells']),
    tipsIt: JSON.stringify(['La barra EZ riduce lo stress sul polso','I gomiti devono rimanere fissi puntando al soffitto','Può essere eseguito anche con manubri']),
    breathingEn: 'Inhale on descent, exhale on extension.',
    breathingIt: 'Inspira in discesa, espira nell\'estensione.',
    alternatives: JSON.stringify(['close-grip-bench', 'cable-overhead-extension', 'dumbbell-overhead-extension']),
    tags: JSON.stringify(['isolation','triceps','barbell','lying']),
  },
  {
    id: 'tricep-dips', slug: 'tricep-dips',
    nameEn: 'Tricep Dips', nameIt: 'Dip ai Parallele',
    descriptionEn: 'Bodyweight tricep exercise using parallel bars or bench. Can be weighted for progression.',
    descriptionIt: 'Esercizio per i tricipiti a corpo libero alle parallele o sulla panca. Può essere zavorrato per la progressione.',
    primaryMuscles: JSON.stringify(['triceps']),
    secondaryMuscles: JSON.stringify(['chest', 'front_delts']),
    equipmentId: 'dip_station', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Grip parallel bars, straight body position','Lean forward slightly for tricep focus','Lower by bending elbows, keep them close','Dip until upper arms parallel','Press back up']),
    instructionsIt: JSON.stringify(['Impugna le parallele, posizione del corpo dritta','Inclina leggermente in avanti per focus sui tricipiti','Abbassa piegando i gomiti, tienili vicini','Scendi finché le braccia superiori sono parallele','Spingi di nuovo su']),
    mistakesEn: JSON.stringify(['Leaning too forward (becomes chest-focused)','Flaring elbows wide','Not reaching depth']),
    mistakesIt: JSON.stringify(['Inclinarsi troppo in avanti (diventa focus petto)','Aprire i gomiti','Non raggiungere la profondità']),
    tipsEn: JSON.stringify(['More upright = more tricep','Add weight with dip belt for progression','Good shoulder mobility required']),
    tipsIt: JSON.stringify(['Più eretto = più tricipite','Aggiungi peso con cintura per le trazioni per progressione','Buona mobilità delle spalle richiesta']),
    breathingEn: 'Inhale on descent, exhale on press.',
    breathingIt: 'Inspira in discesa, espira nella spinta.',
    alternatives: JSON.stringify(['close-grip-bench', 'cable-pushdown', 'bench-dips']),
    tags: JSON.stringify(['compound','triceps','bodyweight','dips']),
  },
  {
    id: 'cable-pushdown', slug: 'cable-pushdown',
    nameEn: 'Cable Tricep Pushdown', nameIt: 'Pushdown ai Cavi',
    descriptionEn: 'Cable isolation for triceps. Constant tension and great for pump and detail work.',
    descriptionIt: 'Isolamento dei tricipiti ai cavi. Tensione costante e ottimo per la congestione e il lavoro di dettaglio.',
    primaryMuscles: JSON.stringify(['triceps']),
    secondaryMuscles: JSON.stringify([]),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Set cable at head height','Grab straight bar or rope','Elbows fixed at sides','Push down to full extension','Control return to 90°']),
    instructionsIt: JSON.stringify(['Imposta il cavo all\'altezza della testa','Prendi la barra dritta o la corda','Gomiti fissi ai fianchi','Spingi giù fino alla piena estensione','Controlla il ritorno a 90°']),
    mistakesEn: JSON.stringify(['Elbows flaring/moving','Leaning over bar','Not reaching full extension']),
    mistakesIt: JSON.stringify(['Gomiti che si aprono/muovono','Inclinarsi sulla barra','Non raggiungere la piena estensione']),
    tipsEn: JSON.stringify(['Rope allows more supination at bottom','Reverse grip targets lateral head more','High reps (12-20) common']),
    tipsIt: JSON.stringify(['La corda permette più supinazione in basso','La presa inversa colpisce più la testa laterale','Rep alte (12-20) comuni']),
    breathingEn: 'Exhale on pushdown, inhale on return.',
    breathingIt: 'Espira nel pushdown, inspira nel ritorno.',
    alternatives: JSON.stringify(['skull-crusher', 'close-grip-bench', 'overhead-cable-extension']),
    tags: JSON.stringify(['isolation','triceps','cable','pushdown']),
  },
  {
    id: 'overhead-tricep-extension', slug: 'overhead-tricep-extension',
    nameEn: 'Overhead Tricep Extension', nameIt: 'Estensione Tricipiti in Alto',
    descriptionEn: 'Overhead tricep extension with dumbbell or cable. Best for the long head stretch.',
    descriptionIt: 'Estensione dei tricipiti in alto con manubrio o cavo. Migliore per l\'allungamento della testa lunga.',
    primaryMuscles: JSON.stringify(['triceps']),
    secondaryMuscles: JSON.stringify([]),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Hold dumbbell overhead with both hands','Elbows pointing up, close to head','Lower dumbbell behind head','Extend arms back to top']),
    instructionsIt: JSON.stringify(['Tieni un manubrio in alto con entrambe le mani','Gomiti puntati in alto, vicini alla testa','Abbassa il manubrio dietro la testa','Estendi le braccia di ritorno in cima']),
    mistakesEn: JSON.stringify(['Elbows flaring too wide','Excessive neck strain','Not reaching full extension']),
    mistakesIt: JSON.stringify(['Gomiti troppo aperti','Eccessiva tensione sul collo','Non raggiungere la piena estensione']),
    tipsEn: JSON.stringify(['Great for long head development','Cable version provides constant tension','Keep wrists neutral']),
    tipsIt: JSON.stringify(['Ottimo per lo sviluppo della testa lunga','La versione ai cavi fornisce tensione costante','Mantieni i polsi neutri']),
    breathingEn: 'Inhale on descent, exhale on extension.',
    breathingIt: 'Inspira in discesa, espira nell\'estensione.',
    alternatives: JSON.stringify(['skull-crusher', 'cable-pushdown', 'close-grip-bench']),
    tags: JSON.stringify(['isolation','triceps','overhead','dumbbell']),
  },
  {
    id: 'ez-bar-curl', slug: 'ez-bar-curl',
    nameEn: 'EZ Bar Curl', nameIt: 'Curl con Barra EZ',
    descriptionEn: 'Bicep curl with EZ bar. Reduces wrist strain versus straight bar while still loading effectively.',
    descriptionIt: 'Curl per i bicipiti con barra EZ. Riduce lo stress sul polso rispetto alla barra dritta pur caricando in modo efficace.',
    primaryMuscles: JSON.stringify(['biceps']),
    secondaryMuscles: JSON.stringify(['forearms']),
    equipmentId: 'ez_bar', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Stand with EZ bar, use angled grip','Curl to shoulder height keeping elbows stable','Squeeze at top','Lower with 3s eccentric']),
    instructionsIt: JSON.stringify(['In piedi con barra EZ, usa la presa inclinata','Arriccia fino all\'altezza delle spalle mantenendo i gomiti stabili','Contrai in alto','Abbassa con eccentrico di 3s']),
    mistakesEn: JSON.stringify(['Elbows swinging forward','Using momentum','Wrong grip angle']),
    mistakesIt: JSON.stringify(['Gomiti che oscillano in avanti','Usare slancio','Angolo di presa sbagliato']),
    tipsEn: JSON.stringify(['Good option for those with wrist issues','Similar strength to straight bar','Also good for preacher curl']),
    tipsIt: JSON.stringify(['Buona opzione per chi ha problemi ai polsi','Forza simile alla barra dritta','Ottimo anche per il banco scott']),
    breathingEn: 'Exhale on curl, inhale on descent.',
    breathingIt: 'Espira nel curl, inspira nella discesa.',
    alternatives: JSON.stringify(['barbell-curl', 'dumbbell-curl', 'cable-curl']),
    tags: JSON.stringify(['isolation','biceps','ez-bar','curl']),
  },
]
