import type { NewExercise } from './types'

export const CHEST_EXERCISES: NewExercise[] = [
  {
    id: 'barbell-bench-press', slug: 'barbell-bench-press',
    nameEn: 'Barbell Bench Press', nameIt: 'Panca Piana con Bilanciere',
    descriptionEn: 'The king of chest exercises. A compound horizontal push that builds chest, front delts, and triceps.',
    descriptionIt: 'Il re degli esercizi per il petto. Spinta orizzontale multiarticolare per petto, deltoidi anteriori e tricipiti.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Lie flat on bench, eyes under bar','Grip slightly wider than shoulder width','Unrack bar, lower to mid-chest','Press up explosively to full extension','Repeat']),
    instructionsIt: JSON.stringify(['Sdraiati sulla panca, occhi sotto il bilanciere','Impugna leggermente più largo delle spalle','Sblocca il bilanciere, abbassa al petto','Spingi in modo esplosivo fino all\'estensione completa','Ripeti']),
    mistakesEn: JSON.stringify(['Bouncing bar off chest','Flaring elbows 90°','Lifting hips off bench','Incomplete range of motion']),
    mistakesIt: JSON.stringify(['Rimbalzare il bilanciere sul petto','Aprire i gomiti a 90°','Alzare i fianchi dalla panca','Range di movimento incompleto']),
    tipsEn: JSON.stringify(['Retract and depress scapulae','Arch slightly for stability','Drive feet into floor','Control the descent (2-3s)']),
    tipsIt: JSON.stringify(['Retrarre e abbassare le scapole','Arcuare leggermente per stabilità','Spingere i piedi a terra','Controllare la discesa (2-3s)']),
    breathingEn: 'Inhale on the way down, exhale on the push.',
    breathingIt: 'Inspira durante la discesa, espira durante la spinta.',
    alternatives: JSON.stringify(['dumbbell-bench-press','machine-chest-press','incline-barbell-press']),
    tags: JSON.stringify(['compound','chest','push','strength']),
  },
  {
    id: 'dumbbell-bench-press', slug: 'dumbbell-bench-press',
    nameEn: 'Dumbbell Bench Press', nameIt: 'Panca Piana con Manubri',
    descriptionEn: 'Allows greater range of motion than barbell. Excellent for chest development and correcting imbalances.',
    descriptionIt: 'Permette maggiore range di movimento rispetto al bilanciere. Ottimo per lo sviluppo del petto e correggere squilibri.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Lie on bench, hold dumbbells at chest level','Press up until arms are extended','Lower slowly to chest level','Feel the stretch at the bottom']),
    instructionsIt: JSON.stringify(['Sdraiati sulla panca, tieni i manubri all\'altezza del petto','Spingi verso l\'alto fino all\'estensione','Abbassa lentamente all\'altezza del petto','Senti l\'allungamento in basso']),
    mistakesEn: JSON.stringify(['Dropping dumbbells too low','Not controlling the descent','Touching dumbbells at the top']),
    mistakesIt: JSON.stringify(['Abbassare troppo i manubri','Non controllare la discesa','Toccare i manubri in alto']),
    tipsEn: JSON.stringify(['Neutral or pronated grip','Wider range = more stretch','Squeeze chest at top']),
    tipsIt: JSON.stringify(['Presa neutrale o prona','Maggiore range = più allungamento','Contrai il petto in alto']),
    breathingEn: 'Inhale on descent, exhale on press.',
    breathingIt: 'Inspira in discesa, espira in salita.',
    alternatives: JSON.stringify(['barbell-bench-press','machine-chest-press','cable-chest-fly']),
    tags: JSON.stringify(['compound','chest','push']),
  },
  {
    id: 'incline-barbell-press', slug: 'incline-barbell-press',
    nameEn: 'Incline Barbell Press', nameIt: 'Panca Inclinata con Bilanciere',
    descriptionEn: 'Targets the upper chest and clavicular head. Essential for a complete chest development.',
    descriptionIt: 'Bersaglia il petto alto e il fascio clavicolare. Essenziale per uno sviluppo completo del petto.',
    primaryMuscles: JSON.stringify(['upper_chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Set bench to 30-45°','Grip slightly wider than shoulder width','Lower bar to upper chest','Press up to full extension']),
    instructionsIt: JSON.stringify(['Imposta la panca a 30-45°','Presa leggermente più larga delle spalle','Abbassa il bilanciere al petto alto','Spingi fino all\'estensione completa']),
    mistakesEn: JSON.stringify(['Bench angle too steep (>45°)','Bar path too far back','Flaring elbows excessively']),
    mistakesIt: JSON.stringify(['Angolo troppo ripido (>45°)','Traiettoria troppo posteriore','Aprire eccessivamente i gomiti']),
    tipsEn: JSON.stringify(['30° is optimal for upper chest','Keep elbows at 45-75°','Retract scapulae firmly']),
    tipsIt: JSON.stringify(['30° è ottimale per il petto alto','Mantieni i gomiti a 45-75°','Retrarre fermamente le scapole']),
    breathingEn: 'Inhale down, exhale up.',
    breathingIt: 'Inspira in discesa, espira in salita.',
    alternatives: JSON.stringify(['incline-dumbbell-press','cable-high-fly','machine-incline-press']),
    tags: JSON.stringify(['compound','upper_chest','push']),
  },
  {
    id: 'incline-dumbbell-press', slug: 'incline-dumbbell-press',
    nameEn: 'Incline Dumbbell Press', nameIt: 'Panca Inclinata con Manubri',
    descriptionEn: 'Upper chest focus with greater freedom of movement. Excellent for muscle development.',
    descriptionIt: 'Enfasi sul petto alto con maggiore libertà di movimento. Eccellente per lo sviluppo muscolare.',
    primaryMuscles: JSON.stringify(['upper_chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Set bench to 30-45°','Hold dumbbells at shoulder level','Press up and slightly inward','Lower with control']),
    instructionsIt: JSON.stringify(['Imposta la panca a 30-45°','Tieni i manubri all\'altezza delle spalle','Spingi verso l\'alto e leggermente verso l\'interno','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Too steep angle','Unstable wrists','Not feeling upper chest']),
    mistakesIt: JSON.stringify(['Angolo troppo ripido','Polsi instabili','Non sentire il petto alto']),
    tipsEn: JSON.stringify(['Aim for the upper chest/clavicle area','Slight inward arc at top','Keep core tight']),
    tipsIt: JSON.stringify(['Punta all\'area petto alto/clavicola','Leggero arco verso l\'interno in alto','Mantieni il core attivo']),
    breathingEn: 'Inhale down, exhale up.',
    breathingIt: 'Inspira in discesa, espira in salita.',
    alternatives: JSON.stringify(['incline-barbell-press','cable-high-fly']),
    tags: JSON.stringify(['compound','upper_chest','push']),
  },
  {
    id: 'decline-barbell-press', slug: 'decline-barbell-press',
    nameEn: 'Decline Barbell Press', nameIt: 'Panca Declinata con Bilanciere',
    descriptionEn: 'Targets the lower chest. Reduces shoulder strain compared to flat bench.',
    descriptionIt: 'Bersaglia il petto inferiore. Riduce il carico sulle spalle rispetto alla panca piana.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['triceps', 'front_delts']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Set bench to -15 to -30°','Secure feet','Lower bar to lower chest','Press to full extension']),
    instructionsIt: JSON.stringify(['Imposta la panca a -15/-30°','Blocca i piedi','Abbassa il bilanciere al petto basso','Spingi fino all\'estensione']),
    mistakesEn: JSON.stringify(['Excessive decline angle','Not securing feet properly']),
    mistakesIt: JSON.stringify(['Angolo di declinazione eccessivo','Non bloccare correttamente i piedi']),
    tipsEn: JSON.stringify(['15-30° is sufficient','Reduces anterior deltoid strain']),
    tipsIt: JSON.stringify(['15-30° è sufficiente','Riduce il carico sul deltoide anteriore']),
    breathingEn: 'Inhale down, exhale up.',
    breathingIt: 'Inspira in discesa, espira in salita.',
    alternatives: JSON.stringify(['decline-dumbbell-press','cable-low-fly','dips']),
    tags: JSON.stringify(['compound','chest','push']),
  },
  {
    id: 'dumbbell-fly', slug: 'dumbbell-fly',
    nameEn: 'Dumbbell Fly', nameIt: 'Croci con Manubri',
    descriptionEn: 'Isolation exercise for chest. Provides excellent muscle stretch.',
    descriptionIt: 'Esercizio di isolamento per il petto. Fornisce un eccellente allungamento muscolare.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie flat, arms extended over chest','Lower in arc with slight elbow bend','Feel chest stretch','Bring arms back together squeezing chest']),
    instructionsIt: JSON.stringify(['Sdraiati, braccia estese sopra il petto','Abbassa ad arco con leggera flessione del gomito','Senti l\'allungamento del petto','Riporta le braccia insieme contraendo il petto']),
    mistakesEn: JSON.stringify(['Straightening elbows completely','Going too heavy','Losing arc movement']),
    mistakesIt: JSON.stringify(['Estendere completamente i gomiti','Usare peso eccessivo','Perdere il movimento ad arco']),
    tipsEn: JSON.stringify(['Use lighter weight than press','Slight permanent elbow bend','Focus on the stretch']),
    tipsIt: JSON.stringify(['Usa peso minore della panca','Leggera flessione permanente del gomito','Focalizzati sull\'allungamento']),
    breathingEn: 'Inhale opening, exhale closing.',
    breathingIt: 'Inspira in apertura, espira in chiusura.',
    alternatives: JSON.stringify(['cable-chest-fly','pec-deck','cable-high-fly']),
    tags: JSON.stringify(['isolation','chest','stretch']),
  },
  {
    id: 'cable-chest-fly', slug: 'cable-chest-fly',
    nameEn: 'Cable Chest Fly', nameIt: 'Croci ai Cavi',
    descriptionEn: 'Constant tension throughout the movement. Excellent for chest isolation and definition.',
    descriptionIt: 'Tensione costante durante tutto il movimento. Eccellente per isolamento e definizione del petto.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cables at shoulder height','Stand in middle, step forward','Bring handles together in front of chest','Control return']),
    instructionsIt: JSON.stringify(['Imposta i cavi all\'altezza delle spalle','Stai al centro, fai un passo avanti','Porta le maniglie davanti al petto','Controlla il ritorno']),
    mistakesEn: JSON.stringify(['Using too much weight','Losing tension at peak','Elbows fully straightened']),
    mistakesIt: JSON.stringify(['Usare troppo peso','Perdere tensione al picco','Gomiti completamente estesi']),
    tipsEn: JSON.stringify(['Slight forward lean','Squeeze at peak contraction','Cross hands slightly at peak']),
    tipsIt: JSON.stringify(['Leggera inclinazione in avanti','Contrai al picco di contrazione','Incrocia leggermente le mani al picco']),
    breathingEn: 'Exhale as you bring handles together.',
    breathingIt: 'Espira mentre porti le maniglie insieme.',
    alternatives: JSON.stringify(['dumbbell-fly','pec-deck']),
    tags: JSON.stringify(['isolation','chest','cable']),
  },
  {
    id: 'cable-high-fly', slug: 'cable-high-fly',
    nameEn: 'Cable High Fly (Lower Chest)', nameIt: 'Cavi Alti (Petto Basso)',
    descriptionEn: 'Cables set high, pull down and together. Focuses on lower chest.',
    descriptionIt: 'Cavi impostati in alto, tira verso il basso e insieme. Enfasi sul petto inferiore.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cables above head','Stand in center','Pull down and together in arc','Control return to start']),
    instructionsIt: JSON.stringify(['Imposta i cavi sopra la testa','Stai al centro','Tira verso il basso e insieme ad arco','Controlla il ritorno']),
    mistakesEn: JSON.stringify(['Bending elbows too much','Losing posture']),
    mistakesIt: JSON.stringify(['Flettere troppo i gomiti','Perdere la postura']),
    tipsEn: JSON.stringify(['Lean slightly forward','Feel lower chest squeeze','Light weight, high reps']),
    tipsIt: JSON.stringify(['Inclina leggermente in avanti','Senti la contrazione del petto basso','Peso leggero, alte ripetizioni']),
    breathingEn: 'Exhale on the pull.',
    breathingIt: 'Espira durante la trazione.',
    alternatives: JSON.stringify(['cable-chest-fly','dips']),
    tags: JSON.stringify(['isolation','chest','cable']),
  },
  {
    id: 'pec-deck', slug: 'pec-deck',
    nameEn: 'Pec Deck (Machine Fly)', nameIt: 'Pec Deck (Macchina Farfalla)',
    descriptionEn: 'Machine fly. Safe, guided movement. Perfect for isolating the chest.',
    descriptionIt: 'Croci alla macchina. Movimento guidato e sicuro. Perfetto per isolare il petto.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Adjust seat so handles are at chest level','Grip handles','Bring together squeezing chest','Control return']),
    instructionsIt: JSON.stringify(['Regola il sedile affinché le maniglie siano all\'altezza del petto','Afferra le maniglie','Porta insieme contraendo il petto','Controlla il ritorno']),
    mistakesEn: JSON.stringify(['Seat too high or low','Not feeling chest contraction','Using momentum']),
    mistakesIt: JSON.stringify(['Sedile troppo alto o basso','Non sentire la contrazione del petto','Usare l\'inerzia']),
    tipsEn: JSON.stringify(['Full range of motion','Pause 1s at peak contraction','Great for beginners']),
    tipsIt: JSON.stringify(['Range di movimento completo','Pausa 1s al picco','Ottimo per principianti']),
    breathingEn: 'Exhale when closing.',
    breathingIt: 'Espira in chiusura.',
    alternatives: JSON.stringify(['cable-chest-fly','dumbbell-fly']),
    tags: JSON.stringify(['isolation','chest','machine']),
  },
  {
    id: 'machine-chest-press', slug: 'machine-chest-press',
    nameEn: 'Machine Chest Press', nameIt: 'Chest Press alla Macchina',
    descriptionEn: 'Guided chest press. Safe and effective. Good for beginners and high-volume training.',
    descriptionIt: 'Panca guidata. Sicura ed efficace. Ottima per principianti e allenamenti ad alto volume.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Adjust seat and handles','Press forward to full extension','Control return to chest level','Keep back against pad']),
    instructionsIt: JSON.stringify(['Regola sedile e maniglie','Spingi in avanti fino all\'estensione','Controlla il ritorno all\'altezza del petto','Mantieni la schiena contro il supporto']),
    mistakesEn: JSON.stringify(['Hands too high or low','Not controlling return','Leaning forward']),
    mistakesIt: JSON.stringify(['Mani troppo alte o basse','Non controllare il ritorno','Sporgersi in avanti']),
    tipsEn: JSON.stringify(['Great for beginners','Use as finisher after barbell work','Can do drop sets easily']),
    tipsIt: JSON.stringify(['Ottima per principianti','Usare come finitura dopo il bilanciere','Facile per drop set']),
    breathingEn: 'Exhale pressing out.',
    breathingIt: 'Espira spingendo in avanti.',
    alternatives: JSON.stringify(['barbell-bench-press','dumbbell-bench-press']),
    tags: JSON.stringify(['compound','chest','machine']),
  },
  {
    id: 'push-up', slug: 'push-up',
    nameEn: 'Push-up', nameIt: 'Piegamenti sulle Braccia',
    descriptionEn: 'Fundamental bodyweight exercise. Works chest, triceps, and front delts.',
    descriptionIt: 'Esercizio base a corpo libero. Lavora petto, tricipiti e deltoidi anteriori.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['triceps', 'front_delts']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Start in plank position, hands slightly wider than shoulders','Lower body until chest nearly touches ground','Push back up explosively','Keep body straight throughout']),
    instructionsIt: JSON.stringify(['Inizia in posizione plank, mani leggermente più larghe delle spalle','Abbassa il corpo fino a quasi toccare terra con il petto','Spingi verso l\'alto in modo esplosivo','Mantieni il corpo dritto']),
    mistakesEn: JSON.stringify(['Hips sagging','Flaring elbows out','Incomplete range of motion','Head drooping']),
    mistakesIt: JSON.stringify(['Fianchi che cedono','Gomiti troppo aperti','Range di movimento incompleto','Testa che cade']),
    tipsEn: JSON.stringify(['Hands below shoulders not in front','Elbows at 45° angle','Squeeze glutes and core','Chest to floor for full ROM']),
    tipsIt: JSON.stringify(['Mani sotto le spalle non davanti','Gomiti a 45°','Contrai glutei e core','Petto a terra per ROM completo']),
    breathingEn: 'Inhale going down, exhale pushing up.',
    breathingIt: 'Inspira scendendo, espira salendo.',
    alternatives: JSON.stringify(['barbell-bench-press','machine-chest-press','dips']),
    tags: JSON.stringify(['compound','chest','bodyweight']),
  },
  {
    id: 'wide-push-up', slug: 'wide-push-up',
    nameEn: 'Wide Push-up', nameIt: 'Piegamenti Larghi',
    descriptionEn: 'Wider hand placement increases chest activation.',
    descriptionIt: 'Posizione delle mani più larga aumenta l\'attivazione del petto.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Place hands wider than shoulders','Lower chest between hands','Push back up']),
    instructionsIt: JSON.stringify(['Metti le mani più larghe delle spalle','Abbassa il petto tra le mani','Spingiti su']),
    mistakesEn: JSON.stringify(['Too wide causes shoulder strain']),
    mistakesIt: JSON.stringify(['Troppo larghezza causa tensione alla spalla']),
    tipsEn: JSON.stringify(['1.5x shoulder width is optimal']),
    tipsIt: JSON.stringify(['1,5x larghezza spalle è ottimale']),
    breathingEn: 'Inhale down, exhale up.',
    breathingIt: 'Inspira giù, espira su.',
    alternatives: JSON.stringify(['push-up','dumbbell-fly']),
    tags: JSON.stringify(['chest','bodyweight']),
  },
  {
    id: 'dips', slug: 'dips',
    nameEn: 'Dips (Chest)', nameIt: 'Dips (Petto)',
    descriptionEn: 'Compound bodyweight exercise targeting lower chest and triceps when leaning forward.',
    descriptionIt: 'Esercizio multiarticolare a corpo libero. Con busto inclinato bersaglia il petto inferiore e i tricipiti.',
    primaryMuscles: JSON.stringify(['chest']),
    secondaryMuscles: JSON.stringify(['triceps', 'front_delts']),
    equipmentId: 'dip_station', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Grip parallel bars','Lean forward 30-45° for chest emphasis','Lower until arms at 90°','Press back up']),
    instructionsIt: JSON.stringify(['Afferra le parallele','Inclina in avanti 30-45° per enfasi sul petto','Scendi fino ai 90°','Spingi su']),
    mistakesEn: JSON.stringify(['Going too deep with shoulder pain','Not leaning forward for chest']),
    mistakesIt: JSON.stringify(['Scendere troppo con dolore alla spalla','Non inclinarsi in avanti per il petto']),
    tipsEn: JSON.stringify(['Lean forward for chest','Stay upright for triceps','Add weight when bodyweight is easy']),
    tipsIt: JSON.stringify(['Inclina in avanti per il petto','Stai dritto per i tricipiti','Aggiungi peso quando il corpo libero è facile']),
    breathingEn: 'Inhale going down, exhale pressing up.',
    breathingIt: 'Inspira scendendo, espira salendo.',
    alternatives: JSON.stringify(['barbell-bench-press','cable-chest-fly']),
    tags: JSON.stringify(['compound','chest','bodyweight']),
  },
  {
    id: 'landmine-press', slug: 'landmine-press',
    nameEn: 'Landmine Press', nameIt: 'Landmine Press',
    descriptionEn: 'Arcing press motion. Great for upper chest and shoulder health.',
    descriptionIt: 'Movimento di spinta ad arco. Ottimo per il petto alto e la salute delle spalle.',
    primaryMuscles: JSON.stringify(['upper_chest']),
    secondaryMuscles: JSON.stringify(['front_delts', 'triceps']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Fix one end of barbell','Cup the other end','Press forward and slightly up','Control return']),
    instructionsIt: JSON.stringify(['Blocca un\'estremità del bilanciere','Tieni l\'altra estremità con entrambe le mani','Spingi in avanti e leggermente in alto','Controlla il ritorno']),
    mistakesEn: JSON.stringify(['Too much weight','Leaning back excessively']),
    mistakesIt: JSON.stringify(['Troppo peso','Inclinarsi eccessivamente all\'indietro']),
    tipsEn: JSON.stringify(['Arc naturally follows proper upper chest path','Good for shoulder rehab']),
    tipsIt: JSON.stringify(['L\'arco segue naturalmente il percorso corretto','Buono per la riabilitazione della spalla']),
    breathingEn: 'Exhale on press.',
    breathingIt: 'Espira nella spinta.',
    alternatives: JSON.stringify(['incline-barbell-press','cable-high-fly']),
    tags: JSON.stringify(['compound','upper_chest','push']),
  },
]
