import type { NewExercise } from './types'

export const backExercises2: NewExercise[] = [
  {
    id: 'chest-supported-row', slug: 'chest-supported-row', nameEn: 'Chest-Supported Row', nameIt: 'Rematore con supporto al petto',
    primaryMuscles: JSON.stringify(['back']), secondaryMuscles: JSON.stringify(['biceps', 'rear-delts']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set incline bench to 30-45°', 'Lie face down on bench', 'Row dumbbells toward hips', 'Squeeze back at top']),
    instructionsIt: JSON.stringify(['Imposta la panca inclinata a 30-45°', 'Sdraiati a pancia in giù', 'Fai remare i manubri verso i fianchi', 'Stringi la schiena in cima']),
    mistakesEn: JSON.stringify(['Shrugging shoulders', 'Using momentum', 'Not retracting shoulder blades']),
    mistakesIt: JSON.stringify(['Alzare le spalle', 'Usare lo slancio', 'Non retrarre le scapole']),
    tipsEn: JSON.stringify(['Eliminates lower back fatigue', 'Great for back focus without spinal loading']),
    tipsIt: JSON.stringify(['Elimina la fatica lombare', 'Ottimo per la schiena senza carico spinale']),
    alternatives: JSON.stringify(['dumbbell-row', 'cable-row']),
    tags: JSON.stringify(['back', 'dumbbell', 'pull']),
  },
  {
    id: 'meadows-row', slug: 'meadows-row', nameEn: 'Meadows Row', nameIt: 'Meadows Row',
    primaryMuscles: JSON.stringify(['back']), secondaryMuscles: JSON.stringify(['biceps']),
    equipmentId: 'barbell', difficulty: 'advanced', movementType: 'pull',
    instructionsEn: JSON.stringify(['Stand perpendicular to loaded barbell end', 'Hinge and grab the end with one hand', 'Row toward hip, elbow high', 'Control the descent']),
    instructionsIt: JSON.stringify(['Stai perpendicolare all\'estremità del bilanciere', 'Piega e afferra con una mano', 'Rema verso il fianco, gomito alto', 'Controlla la discesa']),
    mistakesEn: JSON.stringify(['Rotating too much', 'Not getting full range of motion', 'Using too much weight']),
    mistakesIt: JSON.stringify(['Ruotare troppo', 'Non usare il ROM completo', 'Troppo peso']),
    tipsEn: JSON.stringify(['Creates great stretch at bottom', 'Superior lat activation', 'Keep non-working hand on thigh for balance']),
    tipsIt: JSON.stringify(['Crea ottimo stretching', 'Eccellente attivazione del lat', 'Usa la mano libera per l\'equilibrio']),
    alternatives: JSON.stringify(['dumbbell-row', 'barbell-row']),
    tags: JSON.stringify(['back', 'barbell', 'unilateral']),
  },
  {
    id: 'seated-cable-row-wide', slug: 'seated-cable-row-wide', nameEn: 'Wide-Grip Cable Row', nameIt: 'Rematore ai cavi presa larga',
    primaryMuscles: JSON.stringify(['upper-back']), secondaryMuscles: JSON.stringify(['rear-delts', 'biceps']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Use lat pulldown bar attachment', 'Sit at cable row station', 'Row bar to upper abdomen', 'Squeeze shoulder blades together']),
    instructionsIt: JSON.stringify(['Usa il bilanciere del lat pulldown', 'Siediti alla stazione per il rematore', 'Porta il bilanciere all\'addome alto', 'Stringi le scapole']),
    mistakesEn: JSON.stringify(['Leaning back too much', 'Pulling to chest instead of abdomen', 'Not squeezing at peak']),
    mistakesIt: JSON.stringify(['Inclinarsi troppo indietro', 'Tirare al petto invece dell\'addome', 'Non contrarre al picco']),
    tipsEn: JSON.stringify(['Targets upper back and rear delts more than narrow grip', 'Keep chest up throughout']),
    tipsIt: JSON.stringify(['Lavora di più la schiena alta e i deltoidi posteriori', 'Mantieni il petto alto']),
    alternatives: JSON.stringify(['cable-row', 'barbell-row']),
    tags: JSON.stringify(['back', 'cable', 'upper-back']),
  },
  {
    id: 'single-arm-lat-pulldown', slug: 'single-arm-lat-pulldown', nameEn: 'Single-Arm Lat Pulldown', nameIt: 'Lat machine monobraccio',
    primaryMuscles: JSON.stringify(['lats']), secondaryMuscles: JSON.stringify(['biceps']),
    equipmentId: 'cable', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Attach single handle to cable', 'Sit, grip with one hand', 'Pull down toward shoulder', 'Slow return to full stretch']),
    instructionsIt: JSON.stringify(['Attacca la maniglia singola al cavo', 'Siediti, afferra con una mano', 'Tira verso la spalla', 'Ritorno lento a stretching completo']),
    mistakesEn: JSON.stringify(['Rotating too much', 'Not getting full lat stretch', 'Using biceps instead of back']),
    mistakesIt: JSON.stringify(['Ruotare troppo', 'Non fare stretching completo del lat', 'Usare i bicipiti invece della schiena']),
    tipsEn: JSON.stringify(['Great for fixing lat imbalances', 'Focus on elbow driving down toward hip']),
    tipsIt: JSON.stringify(['Ottimo per correggere squilibri dei lat', 'Immagina il gomito che va verso il fianco']),
    alternatives: JSON.stringify(['lat-pulldown', 'pull-up']),
    tags: JSON.stringify(['back', 'cable', 'unilateral']),
  },
  {
    id: 'pendlay-row', slug: 'pendlay-row', nameEn: 'Pendlay Row', nameIt: 'Pendlay Row',
    primaryMuscles: JSON.stringify(['back']), secondaryMuscles: JSON.stringify(['biceps', 'core']),
    equipmentId: 'barbell', difficulty: 'advanced', movementType: 'pull',
    instructionsEn: JSON.stringify(['Bar starts on floor each rep', 'Hip hinge to horizontal torso', 'Explosively row bar to chest', 'Lower bar to floor completely']),
    instructionsIt: JSON.stringify(['Il bilanciere parte dal pavimento ogni ripetizione', 'Piega i fianchi a busto orizzontale', 'Rema esplosivamente il bilanciere al petto', 'Abbassa completamente al pavimento']),
    mistakesEn: JSON.stringify(['Using momentum', 'Torso not parallel to floor', 'Bar not returning to floor']),
    mistakesIt: JSON.stringify(['Usare lo slancio', 'Busto non parallelo al pavimento', 'Bilanciere non ritorna al pavimento']),
    tipsEn: JSON.stringify(['More explosive and heavier than bent-over row', 'Forces strict form each rep', 'Great for strength development']),
    tipsIt: JSON.stringify(['Più esplosivo e pesante del rematore', 'Forza la forma corretta ogni ripetizione', 'Ottimo per lo sviluppo della forza']),
    alternatives: JSON.stringify(['barbell-row', 'deadlift']),
    tags: JSON.stringify(['back', 'barbell', 'strength', 'explosive']),
  },
]
