import type { NewExercise } from './types'

export const CARDIO_EXERCISES: NewExercise[] = [
  {
    id: 'burpee', slug: 'burpee',
    nameEn: 'Burpee', nameIt: 'Burpee',
    descriptionEn: 'Full body conditioning exercise combining squat, plank, push-up and jump.',
    descriptionIt: 'Esercizio di condizionamento totale che combina squat, plank, piegamento e salto.',
    primaryMuscles: JSON.stringify(['quads', 'chest', 'abs']),
    secondaryMuscles: JSON.stringify(['glutes', 'triceps', 'front_delts']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Stand feet shoulder-width','Squat down, place hands on floor','Jump feet back to push-up position','Perform push-up (optional)','Jump feet back to squat','Jump up with arms overhead']),
    instructionsIt: JSON.stringify(['In piedi piedi alla larghezza delle spalle','Accovacciati, metti le mani a terra','Salta i piedi indietro in posizione di piegamento','Esegui un piegamento (opzionale)','Salta i piedi di ritorno allo squat','Salta in alto con le braccia sopra la testa']),
    mistakesEn: JSON.stringify(['Landing with locked knees','Sagging hips in plank','No hip extension in jump']),
    mistakesIt: JSON.stringify(['Atterrare con le ginocchia bloccate','Fianchi che cedono nel plank','Nessuna estensione dell\'anca nel salto']),
    tipsEn: JSON.stringify(['Scale by removing push-up or jump','Excellent HIIT exercise','Count reps or time intervals']),
    tipsIt: JSON.stringify(['Scala rimuovendo il piegamento o il salto','Eccellente esercizio HIIT','Conta le rep o gli intervalli di tempo']),
    breathingEn: 'Rhythmic breathing, exhale on jump.',
    breathingIt: 'Respiro ritmico, espira nel salto.',
    alternatives: JSON.stringify(['mountain-climber', 'jumping-jack', 'squat-jump']),
    tags: JSON.stringify(['cardio','full-body','bodyweight','hiit']),
  },
  {
    id: 'jump-rope', slug: 'jump-rope',
    nameEn: 'Jump Rope', nameIt: 'Corda per Saltare',
    descriptionEn: 'Classic cardio tool. Improves coordination, calf strength and cardiovascular fitness.',
    descriptionIt: 'Classico strumento cardio. Migliora coordinazione, forza dei polpacci e fitness cardiovascolare.',
    primaryMuscles: JSON.stringify(['calves']),
    secondaryMuscles: JSON.stringify(['abs', 'front_delts', 'forearms']),
    equipmentId: 'cardio', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Hold handles at hip level','Jump 1-2" off ground','Land on balls of feet','Keep elbows close to body','Wrists do the rotation']),
    instructionsIt: JSON.stringify(['Tieni i manici all\'altezza dei fianchi','Salta 2-3cm da terra','Atterra sulle punte dei piedi','Mantieni i gomiti vicini al corpo','I polsi fanno la rotazione']),
    mistakesEn: JSON.stringify(['Jumping too high','Landing on heels','Stiff ankles']),
    mistakesIt: JSON.stringify(['Saltare troppo in alto','Atterrare sui talloni','Caviglie rigide']),
    tipsEn: JSON.stringify(['Start with single-unders','Progress to double-unders','Great warm-up for any workout']),
    tipsIt: JSON.stringify(['Inizia con i salti singoli','Progredisci ai double-unders','Ottimo riscaldamento per qualsiasi allenamento']),
    breathingEn: 'Rhythm breathing with jump cadence.',
    breathingIt: 'Respiro ritmico con la cadenza del salto.',
    alternatives: JSON.stringify(['high-knees', 'jumping-jack', 'burpee']),
    tags: JSON.stringify(['cardio','coordination','calves','conditioning']),
  },
  {
    id: 'box-jump', slug: 'box-jump',
    nameEn: 'Box Jump', nameIt: 'Box Jump',
    descriptionEn: 'Plyometric exercise developing explosive leg power and power endurance.',
    descriptionIt: 'Esercizio pliometrico che sviluppa la potenza esplosiva delle gambe e la resistenza alla potenza.',
    primaryMuscles: JSON.stringify(['quads', 'glutes']),
    secondaryMuscles: JSON.stringify(['calves', 'hamstrings', 'abs']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Stand facing box, feet shoulder-width','Swing arms back, bend knees','Explode upward, swing arms forward','Land softly with knees bent','Stand fully on box, step down']),
    instructionsIt: JSON.stringify(['In piedi di fronte alla box, piedi alla larghezza delle spalle','Porta le braccia indietro, piega le ginocchia','Esplodi verso l\'alto, porta le braccia in avanti','Atterra morbidamente con le ginocchia piegate','Stai in piedi sulla box, scendi camminando']),
    mistakesEn: JSON.stringify(['Landing with stiff legs','Jumping down instead of stepping','Too high box before ready']),
    mistakesIt: JSON.stringify(['Atterrare con le gambe rigide','Saltare giù invece di scendere','Box troppo alta prima di essere pronti']),
    tipsEn: JSON.stringify(['Land where you took off','Step down for safety','Progression: height increase or load']),
    tipsIt: JSON.stringify(['Atterra dove sei partito','Scendi camminando per sicurezza','Progressione: aumento altezza o carico']),
    breathingEn: 'Exhale on jump, inhale on landing.',
    breathingIt: 'Espira nel salto, inspira nell\'atterraggio.',
    alternatives: JSON.stringify(['squat-jump', 'step-up', 'barbell-squat']),
    tags: JSON.stringify(['plyometric','power','legs','conditioning']),
  },
  {
    id: 'rowing-machine', slug: 'rowing-machine',
    nameEn: 'Rowing Machine', nameIt: 'Vogatore',
    descriptionEn: 'Full body cardiovascular exercise. Low impact, high calorie burn, excellent conditioning.',
    descriptionIt: 'Esercizio cardiovascolare per tutto il corpo. Basso impatto, alto consumo calorico, ottimo condizionamento.',
    primaryMuscles: JSON.stringify(['lats', 'upper_back']),
    secondaryMuscles: JSON.stringify(['glutes', 'hamstrings', 'biceps', 'abs']),
    equipmentId: 'cardio', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Sit on machine, strap feet in','Start with legs extended, lean back ~10°','Drive with legs first, then lean back, then arms','Arms come in to chest, then reverse sequence: arms, lean forward, legs']),
    instructionsIt: JSON.stringify(['Siediti sulla macchina, assicura i piedi','Inizia con le gambe estese, inclinati indietro ~10°','Prima spingi con le gambe, poi inclina indietro, poi le braccia','Le braccia arrivano al petto, poi sequenza inversa: braccia, inclina in avanti, gambe']),
    mistakesEn: JSON.stringify(['Opening back before legs extend','Arms pulling before legs finish','Leaning back too far']),
    mistakesIt: JSON.stringify(['Aprire la schiena prima che le gambe si estendano','Le braccia tirano prima che le gambe finiscano','Inclinarsi troppo indietro']),
    tipsEn: JSON.stringify(['Sequence: legs-back-arms, arms-back-legs','85% of power from legs','Good for warm-up or steady state']),
    tipsIt: JSON.stringify(['Sequenza: gambe-schiena-braccia, braccia-schiena-gambe','85% della potenza dalle gambe','Buono per riscaldamento o stato stazionario']),
    breathingEn: 'Exhale on drive, inhale on recovery.',
    breathingIt: 'Espira nella spinta, inspira nel recupero.',
    alternatives: JSON.stringify(['pull-up', 'cable-row', 'jump-rope']),
    tags: JSON.stringify(['cardio','full-body','machine','low-impact']),
  },
  {
    id: 'battle-ropes', slug: 'battle-ropes',
    nameEn: 'Battle Ropes', nameIt: 'Corde da Battaglia',
    descriptionEn: 'High intensity conditioning using heavy ropes. Builds power and cardiovascular fitness.',
    descriptionIt: 'Condizionamento ad alta intensità con corde pesanti. Sviluppa potenza e fitness cardiovascolare.',
    primaryMuscles: JSON.stringify(['front_delts', 'side_delts']),
    secondaryMuscles: JSON.stringify(['biceps', 'triceps', 'abs', 'quads']),
    equipmentId: 'cardio', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Hold one end of each rope','Athletic stance, slight knee bend','Alternate arms up and down (waves)','Keep waves consistent','Work for time intervals']),
    instructionsIt: JSON.stringify(['Tieni un\'estremità di ogni corda','Posizione atletica, leggera flessione delle ginocchia','Alterna le braccia su e giù (onde)','Mantieni le onde costanti','Lavora per intervalli di tempo']),
    mistakesEn: JSON.stringify(['Using only arms (use full body)','Losing wave consistency','Standing too close to anchor']),
    mistakesIt: JSON.stringify(['Usare solo le braccia (usa tutto il corpo)','Perdere la coerenza dell\'onda','Stare troppo vicini all\'ancoraggio']),
    tipsEn: JSON.stringify(['Many wave patterns: alternating, double, outside','Great finisher or HIIT station','30s on/30s off is effective protocol']),
    tipsIt: JSON.stringify(['Molti pattern di onde: alternato, doppio, esterno','Ottimo finisher o stazione HIIT','30s on/30s off è un protocollo efficace']),
    breathingEn: 'Rhythm breathing throughout.',
    breathingIt: 'Respiro ritmico per tutto il movimento.',
    alternatives: JSON.stringify(['burpee', 'jump-rope', 'box-jump']),
    tags: JSON.stringify(['cardio','hiit','power','conditioning']),
  },
  {
    id: 'treadmill-run', slug: 'treadmill-run',
    nameEn: 'Treadmill Run', nameIt: 'Corsa sul Tapis Roulant',
    descriptionEn: 'Controlled running on treadmill. Adjustable speed and incline for varied training.',
    descriptionIt: 'Corsa controllata sul tapis roulant. Velocità e inclinazione regolabili per allenamento vario.',
    primaryMuscles: JSON.stringify(['quads', 'hamstrings', 'calves']),
    secondaryMuscles: JSON.stringify(['glutes', 'abs', 'hip_flexors']),
    equipmentId: 'cardio', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Set desired speed and incline','Maintain upright posture','Land midfoot','Swing arms naturally','Breathe rhythmically']),
    instructionsIt: JSON.stringify(['Imposta velocità e inclinazione desiderate','Mantieni postura eretta','Atterra con il metatarso','Dondola naturalmente le braccia','Respira in modo ritmico']),
    mistakesEn: JSON.stringify(['Holding handrails','Overstriding','Heel striking at high speed']),
    mistakesIt: JSON.stringify(['Tenersi alle maniglie','Passo troppo lungo','Atterrare sul tallone ad alta velocità']),
    tipsEn: JSON.stringify(['Incline 1% to simulate outdoor running','Heart rate zones: 60-70% easy, 80-90% hard','Interval training highly effective']),
    tipsIt: JSON.stringify(['Inclinazione 1% per simulare la corsa all\'aperto','Zone frequenza cardiaca: 60-70% facile, 80-90% duro','L\'allenamento a intervalli è molto efficace']),
    breathingEn: 'Rhythmic breathing, 2 steps inhale, 2 steps exhale.',
    breathingIt: 'Respiro ritmico, 2 passi inspirazione, 2 passi espirazione.',
    alternatives: JSON.stringify(['rowing-machine', 'jump-rope', 'bike']),
    tags: JSON.stringify(['cardio','running','steady-state','machine']),
  },
  {
    id: 'kettlebell-swing', slug: 'kettlebell-swing',
    nameEn: 'Kettlebell Swing', nameIt: 'Swing con Kettlebell',
    descriptionEn: 'Dynamic hip hinge exercise. Builds power, conditions cardiovascular system, and trains posterior chain.',
    descriptionIt: 'Esercizio dinamico di hip hinge. Sviluppa potenza, condiziona il sistema cardiovascolare e allena la catena posteriore.',
    primaryMuscles: JSON.stringify(['glutes', 'hamstrings']),
    secondaryMuscles: JSON.stringify(['lower_back', 'abs', 'front_delts']),
    equipmentId: 'kettlebell', difficulty: 'intermediate', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Stand over kettlebell, feet shoulder-width','Hike kettlebell back between legs','Explosively drive hips forward','Kettlebell floats to chest height','Hike back and repeat']),
    instructionsIt: JSON.stringify(['In piedi sopra il kettlebell, piedi alla larghezza delle spalle','Porta il kettlebell indietro tra le gambe','Spingi esplosivamente i fianchi in avanti','Il kettlebell sale all\'altezza del petto','Riporta indietro e ripeti']),
    mistakesEn: JSON.stringify(['Squatting instead of hinging','Using arms to swing (not hips)','Rounding lower back']),
    mistakesIt: JSON.stringify(['Fare squat invece che hip hinge','Usare le braccia per lo swing (non i fianchi)','Curvare la schiena bassa']),
    tipsEn: JSON.stringify(['Power comes from hip snap, not arms','Dead stop swings for beginners','Russian vs American swing debate']),
    tipsIt: JSON.stringify(['La potenza viene dallo snap dei fianchi, non dalle braccia','Swing con stop per i principianti','Dibattito swing russo vs americano']),
    breathingEn: 'Exhale on hip extension, inhale on hike back.',
    breathingIt: 'Espira nell\'estensione dell\'anca, inspira nel portare indietro.',
    alternatives: JSON.stringify(['deadlift', 'romanian-deadlift', 'hip-thrust']),
    tags: JSON.stringify(['compound','power','hinge','kettlebell','cardio']),
  },
  {
    id: 'jumping-jack', slug: 'jumping-jack',
    nameEn: 'Jumping Jack', nameIt: 'Jumping Jack',
    descriptionEn: 'Classic warm-up and conditioning exercise. Improves coordination and elevates heart rate.',
    descriptionIt: 'Classico esercizio di riscaldamento e condizionamento. Migliora la coordinazione e aumenta la frequenza cardiaca.',
    primaryMuscles: JSON.stringify(['calves', 'quads']),
    secondaryMuscles: JSON.stringify(['front_delts', 'abs']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Stand with feet together, arms at sides','Jump: spread feet wider than shoulder-width, arms up overhead','Jump back to start position','Repeat quickly']),
    instructionsIt: JSON.stringify(['In piedi con i piedi uniti, braccia ai fianchi','Salta: apri i piedi più larghi delle spalle, braccia in alto','Salta di ritorno alla posizione di partenza','Ripeti velocemente']),
    mistakesEn: JSON.stringify(['Landing with locked knees','Arms not reaching overhead','Too slow pace']),
    mistakesIt: JSON.stringify(['Atterrare con le ginocchia bloccate','Braccia che non arrivano sopra la testa','Ritmo troppo lento']),
    tipsEn: JSON.stringify(['Great warm-up', 'Plyo variant: softer landing','Can also do squat jacks for added intensity']),
    tipsIt: JSON.stringify(['Ottimo riscaldamento','Variante plyo: atterraggio morbido','Puoi fare squat jacks per maggiore intensità']),
    breathingEn: 'Natural rhythmic breathing.',
    breathingIt: 'Respiro naturale e ritmico.',
    alternatives: JSON.stringify(['jump-rope', 'mountain-climber', 'high-knees']),
    tags: JSON.stringify(['cardio','warm-up','bodyweight','coordination']),
  },
]
