import type { NewExercise } from './types'

export const armsExercises2: NewExercise[] = [
  {
    id: 'preacher-curl', slug: 'preacher-curl', nameEn: 'Preacher Curl', nameIt: 'Curl al banco Scott',
    primaryMuscles: JSON.stringify(['biceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Sit at preacher bench, upper arms on pad', 'Grip EZ-bar or barbell with underhand grip', 'Curl the bar upward to chin level', 'Lower slowly to full extension']),
    instructionsIt: JSON.stringify(['Siediti al banco Scott, braccia sul cuscino', 'Impugna il bilanciere in presa supina', 'Curl verso il mento', 'Abbassa lentamente a estensione completa']),
    mistakesEn: JSON.stringify(['Lifting upper arms off pad', 'Not lowering to full extension', 'Swinging torso']),
    mistakesIt: JSON.stringify(['Sollevare le braccia dal cuscino', 'Non scendere a estensione completa', 'Dondolare il busto']),
    tipsEn: JSON.stringify(['Excellent bicep isolation', 'Slow eccentric for maximum growth', 'EZ-bar reduces wrist strain']),
    tipsIt: JSON.stringify(['Ottimo isolamento dei bicipiti', 'Eccentrica lenta per massima crescita', 'Il bilanciere EZ riduce lo stress ai polsi']),
    alternatives: JSON.stringify(['barbell-curl', 'concentration-curl']),
    tags: JSON.stringify(['biceps', 'isolation', 'barbell']),
  },
  {
    id: 'concentration-curl', slug: 'concentration-curl', nameEn: 'Concentration Curl', nameIt: 'Curl di concentrazione',
    primaryMuscles: JSON.stringify(['biceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Sit on bench, lean forward', 'Rest elbow against inner thigh', 'Curl dumbbell upward', 'Squeeze bicep at top']),
    instructionsIt: JSON.stringify(['Siediti sulla panca, inclinati avanti', 'Appoggia il gomito sulla coscia', 'Fai curl verso l\'alto', 'Stringi il bicipite in cima']),
    mistakesEn: JSON.stringify(['Moving elbow off thigh', 'Using momentum', 'Not fully extending at bottom']),
    mistakesIt: JSON.stringify(['Muovere il gomito dalla coscia', 'Usare lo slancio', 'Non estendere completamente']),
    tipsEn: JSON.stringify(['Classic Arnold exercise', 'Forces strict form', 'Can pronate slightly at top for peak contraction']),
    tipsIt: JSON.stringify(['Esercizio classico di Arnold', 'Forza la forma corretta', 'Pronarsi leggermente in cima per contrazione massima']),
    alternatives: JSON.stringify(['barbell-curl', 'preacher-curl']),
    tags: JSON.stringify(['biceps', 'isolation', 'dumbbell', 'unilateral']),
  },
  {
    id: 'cable-curl', slug: 'cable-curl', nameEn: 'Cable Curl', nameIt: 'Curl al cavo',
    primaryMuscles: JSON.stringify(['biceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Attach straight bar or rope to low cable', 'Stand upright, grip bar with supinated grip', 'Curl bar to chin keeping elbows stationary', 'Lower with control']),
    instructionsIt: JSON.stringify(['Attacca il bilanciere corto al cavo basso', 'Stai in piedi, impugna in presa supina', 'Fai curl verso il mento, gomiti fermi', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Moving elbows forward', 'Using torso swing', 'Not reaching full extension']),
    mistakesIt: JSON.stringify(['Portare i gomiti avanti', 'Usare lo slancio del busto', 'Non raggiungere l\'estensione completa']),
    tipsEn: JSON.stringify(['Constant tension throughout movement', 'Great for pump work', 'Try rope for neutral grip variation']),
    tipsIt: JSON.stringify(['Tensione costante per tutto il movimento', 'Ottimo per il pump', 'Prova la corda per presa neutra']),
    alternatives: JSON.stringify(['barbell-curl', 'dumbbell-curl']),
    tags: JSON.stringify(['biceps', 'cable', 'isolation']),
  },
  {
    id: 'reverse-curl', slug: 'reverse-curl', nameEn: 'Reverse Curl', nameIt: 'Curl inverso',
    primaryMuscles: JSON.stringify(['brachialis', 'forearms']), secondaryMuscles: JSON.stringify(['biceps']),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hold barbell with overhand (pronated) grip', 'Curl bar up to chin level', 'Lower with control', 'Keep elbows stationary']),
    instructionsIt: JSON.stringify(['Impugna il bilanciere in presa prona', 'Porta il bilanciere al mento', 'Abbassa con controllo', 'Gomiti fermi']),
    mistakesEn: JSON.stringify(['Using wrist to assist', 'Elbows drifting forward', 'Too heavy weight']),
    mistakesIt: JSON.stringify(['Usare il polso per aiutare', 'Gomiti che avanzano', 'Troppo peso']),
    tipsEn: JSON.stringify(['Hits brachialis and forearms more than standard curl', 'Use EZ-bar for easier grip', 'Key for balanced arm development']),
    tipsIt: JSON.stringify(['Colpisce brachiale e avambracci più del curl standard', 'Usa bilanciere EZ per presa più comoda', 'Fondamentale per braccia equilibrate']),
    alternatives: JSON.stringify(['hammer-curl', 'barbell-curl']),
    tags: JSON.stringify(['forearms', 'brachialis', 'barbell']),
  },
  {
    id: 'overhead-tricep-extension', slug: 'overhead-tricep-extension', nameEn: 'Overhead Tricep Extension', nameIt: 'Estensione tricipiti sopra la testa',
    primaryMuscles: JSON.stringify(['triceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Hold one dumbbell with both hands overhead', 'Elbows pointed forward', 'Lower dumbbell behind head', 'Extend arms to starting position']),
    instructionsIt: JSON.stringify(['Tieni un manubrio con entrambe le mani sopra la testa', 'Gomiti rivolti avanti', 'Abbassa il manubrio dietro la testa', 'Estendi le braccia alla posizione iniziale']),
    mistakesEn: JSON.stringify(['Elbows flaring out', 'Arching lower back', 'Not fully extending']),
    mistakesIt: JSON.stringify(['Gomiti che si allargano', 'Inarcamento lombare', 'Non estendere completamente']),
    tipsEn: JSON.stringify(['Great long-head tricep stretch', 'Sit on bench for stability', 'Can also use cable or EZ-bar']),
    tipsIt: JSON.stringify(['Ottimo stretch per il capo lungo del tricipite', 'Siediti per stabilità', 'Puoi usare anche cavo o bilanciere EZ']),
    alternatives: JSON.stringify(['skull-crusher', 'cable-pushdown']),
    tags: JSON.stringify(['triceps', 'dumbbell', 'overhead']),
  },
  {
    id: 'close-grip-bench', slug: 'close-grip-bench', nameEn: 'Close-Grip Bench Press', nameIt: 'Panca presa stretta',
    primaryMuscles: JSON.stringify(['triceps']), secondaryMuscles: JSON.stringify(['chest', 'shoulders']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Grip bar slightly narrower than shoulder width', 'Lower bar to chest keeping elbows tucked', 'Press up explosively', 'Keep elbows close to body throughout']),
    instructionsIt: JSON.stringify(['Impugna il bilanciere leggermente più stretto delle spalle', 'Abbassa al petto, gomiti vicini', 'Spingi esplosivamente', 'Mantieni i gomiti vicini al corpo']),
    mistakesEn: JSON.stringify(['Grip too narrow (wrist pain)', 'Flaring elbows wide', 'Bouncing bar off chest']),
    mistakesIt: JSON.stringify(['Presa troppo stretta (dolore ai polsi)', 'Gomiti troppo larghi', 'Rimbalzare il bilanciere']),
    tipsEn: JSON.stringify(['Shoulder-width grip is optimal for most', 'Great compound tricep builder', 'Pairs well with chest days']),
    tipsIt: JSON.stringify(['Presa larghezza spalle ottimale per la maggior parte', 'Ottimo esercizio compound per i tricipiti', 'Si abbina bene ai giorni petto']),
    alternatives: JSON.stringify(['tricep-dip', 'skull-crusher']),
    tags: JSON.stringify(['triceps', 'barbell', 'compound']),
  },
  {
    id: 'cable-overhead-tricep', slug: 'cable-overhead-tricep', nameEn: 'Cable Overhead Tricep Extension', nameIt: 'Estensione tricipiti sopra la testa al cavo',
    primaryMuscles: JSON.stringify(['triceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Set cable high, attach rope', 'Face away from cable, grab rope overhead', 'Extend arms forward and upward', 'Return slowly']),
    instructionsIt: JSON.stringify(['Imposta il cavo in alto, attacca la corda', 'Volta le spalle al cavo, afferra la corda', 'Estendi le braccia avanti e in alto', 'Ritorna lentamente']),
    mistakesEn: JSON.stringify(['Moving elbows during extension', 'Leaning too far forward', 'Using momentum']),
    mistakesIt: JSON.stringify(['Muovere i gomiti durante l\'estensione', 'Inclinarsi troppo avanti', 'Usare lo slancio']),
    tipsEn: JSON.stringify(['Constant cable tension great for long head', 'Kneel for stability', 'Better stretch than dumbbell version for many']),
    tipsIt: JSON.stringify(['Tensione costante ottima per il capo lungo', 'Inginocchiati per stabilità', 'Migliore stretch della versione con manubrio per molti']),
    alternatives: JSON.stringify(['overhead-tricep-extension', 'skull-crusher']),
    tags: JSON.stringify(['triceps', 'cable', 'overhead']),
  },
  {
    id: 'wrist-curl', slug: 'wrist-curl', nameEn: 'Wrist Curl', nameIt: 'Curl del polso',
    primaryMuscles: JSON.stringify(['forearms']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Sit, rest forearms on thighs with hands over knees', 'Hold barbell with underhand grip', 'Lower weight by extending wrists', 'Curl wrists upward']),
    instructionsIt: JSON.stringify(['Siediti, poggia gli avambracci sulle cosce', 'Impugna il bilanciere in presa supina', 'Abbassa estendendo i polsi', 'Arriccia i polsi verso l\'alto']),
    mistakesEn: JSON.stringify(['Lifting forearms off thighs', 'Using too heavy weight', 'Jerky movements']),
    mistakesIt: JSON.stringify(['Sollevare gli avambracci', 'Troppo peso', 'Movimenti bruschi']),
    tipsEn: JSON.stringify(['Light weight, high reps work best', 'Do reverse wrist curl for balance', 'Forearms rarely need much direct work']),
    tipsIt: JSON.stringify(['Peso leggero, ripetizioni alte', 'Fai anche il curl inverso per equilibrio', 'Gli avambracci raramente necessitano molto lavoro diretto']),
    alternatives: JSON.stringify(['reverse-curl', 'farmer-carry']),
    tags: JSON.stringify(['forearms', 'barbell', 'isolation']),
  },
  {
    id: 'incline-curl', slug: 'incline-curl', nameEn: 'Incline Dumbbell Curl', nameIt: 'Curl con manubri su panca inclinata',
    primaryMuscles: JSON.stringify(['biceps']), secondaryMuscles: JSON.stringify(['brachialis']),
    equipmentId: 'dumbbell', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set bench to 45-60°, lie back with arms hanging', 'Curl dumbbells with supinated grip', 'Hold contraction at top', 'Lower fully for deep stretch']),
    instructionsIt: JSON.stringify(['Imposta la panca a 45-60°, sdraiati con braccia pendenti', 'Fai curl con presa supina', 'Mantieni la contrazione in cima', 'Abbassa completamente per stretching']),
    mistakesEn: JSON.stringify(['Using momentum to swing up', 'Not reaching full stretch at bottom', 'Bench angle too steep']),
    mistakesIt: JSON.stringify(['Usare lo slancio', 'Non raggiungere lo stretch completo', 'Panca troppo ripida']),
    tipsEn: JSON.stringify(['Long head of bicep gets deep stretch at bottom', 'Use lighter weight than standing curl', 'Emphasizes the stretch portion of rep']),
    tipsIt: JSON.stringify(['Il capo lungo del bicipite si stira completamente in basso', 'Usa meno peso dello standing curl', 'Enfatizza la fase di stretch']),
    alternatives: JSON.stringify(['barbell-curl', 'cable-curl']),
    tags: JSON.stringify(['biceps', 'dumbbell', 'stretch']),
  },
  {
    id: 'single-arm-pushdown', slug: 'single-arm-pushdown', nameEn: 'Single-Arm Pushdown', nameIt: 'Pushdown monobraccio',
    primaryMuscles: JSON.stringify(['triceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Set cable high, attach single handle', 'Grip with one hand, elbow at side', 'Push down to full extension', 'Slowly return to starting position']),
    instructionsIt: JSON.stringify(['Imposta il cavo in alto, attacca la maniglia', 'Afferra con una mano, gomito al fianco', 'Spingi verso il basso a estensione completa', 'Ritorna lentamente']),
    mistakesEn: JSON.stringify(['Elbow drifting away from body', 'Leaning over the cable', 'Not fully extending']),
    mistakesIt: JSON.stringify(['Gomito che si allontana dal corpo', 'Inclinarsi verso il cavo', 'Non estendere completamente']),
    tipsEn: JSON.stringify(['Great for fixing tricep imbalances', 'Better isolation than two-arm version', 'Try different handles (rope, D-ring, V-bar)']),
    tipsIt: JSON.stringify(['Ottimo per correggere squilibri dei tricipiti', 'Migliore isolamento della versione bimanuale', 'Prova diverse maniglie']),
    alternatives: JSON.stringify(['cable-pushdown', 'tricep-dip']),
    tags: JSON.stringify(['triceps', 'cable', 'unilateral']),
  },
  {
    id: 'zottman-curl', slug: 'zottman-curl', nameEn: 'Zottman Curl', nameIt: 'Zottman Curl',
    primaryMuscles: JSON.stringify(['biceps', 'forearms']), secondaryMuscles: JSON.stringify(['brachialis']),
    equipmentId: 'dumbbell', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Curl up with supinated (palms up) grip', 'At top, rotate to pronated (palms down)', 'Lower slowly with pronated grip', 'Rotate back to supinated at bottom']),
    instructionsIt: JSON.stringify(['Curl con presa supina', 'In cima, ruota a presa prona', 'Abbassa lentamente con presa prona', 'Ritorna a presa supina in basso']),
    mistakesEn: JSON.stringify(['Rotating too fast', 'Not lowering slowly on way down', 'Elbows moving']),
    mistakesIt: JSON.stringify(['Ruotare troppo veloce', 'Non abbassare lentamente', 'Gomiti che si muovono']),
    tipsEn: JSON.stringify(['Hits both biceps and forearms in one movement', 'Slow eccentric makes it very effective', 'Use lighter weight than regular curl']),
    tipsIt: JSON.stringify(['Lavora bicipiti e avambracci in un solo movimento', 'L\'eccentrica lenta lo rende molto efficace', 'Usa meno peso del curl normale']),
    alternatives: JSON.stringify(['hammer-curl', 'reverse-curl']),
    tags: JSON.stringify(['biceps', 'forearms', 'dumbbell']),
  },
  {
    id: 'tricep-kickback', slug: 'tricep-kickback', nameEn: 'Tricep Kickback', nameIt: 'Kickback tricipiti',
    primaryMuscles: JSON.stringify(['triceps']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Hinge forward at hips, upper arm parallel to floor', 'Extend forearm backward until arm straight', 'Squeeze tricep at full extension', 'Return to starting position']),
    instructionsIt: JSON.stringify(['Inclinati in avanti, braccio parallelo al suolo', 'Estendi l\'avambraccio finché il braccio è teso', 'Stringi il tricipite in estensione', 'Ritorna alla posizione iniziale']),
    mistakesEn: JSON.stringify(['Upper arm not parallel to floor', 'Using too much weight', 'Swinging arm for momentum']),
    mistakesIt: JSON.stringify(['Braccio non parallelo al suolo', 'Troppo peso', 'Usare lo slancio']),
    tipsEn: JSON.stringify(['Use very light weight for good form', 'Squeeze hard at full extension', 'Can also be done with cable for constant tension']),
    tipsIt: JSON.stringify(['Usa peso molto leggero per buona forma', 'Stringi forte in estensione', 'Si può fare anche al cavo per tensione costante']),
    alternatives: JSON.stringify(['cable-pushdown', 'single-arm-pushdown']),
    tags: JSON.stringify(['triceps', 'dumbbell', 'isolation']),
  },
]
