import type { NewExercise } from './types'

export const CORE_EXERCISES: NewExercise[] = [
  {
    id: 'plank', slug: 'plank',
    nameEn: 'Plank', nameIt: 'Plank',
    descriptionEn: 'Foundational isometric core exercise. Builds deep stabilizer strength and endurance.',
    descriptionIt: 'Esercizio isometrico fondamentale per il core. Sviluppa la forza e la resistenza degli stabilizzatori profondi.',
    primaryMuscles: JSON.stringify(['abs', 'obliques']),
    secondaryMuscles: JSON.stringify(['lower_back', 'glutes', 'front_delts']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Forearms on floor, elbows under shoulders','Body forms straight line head to heels','Squeeze glutes and abs','Hold position for time']),
    instructionsIt: JSON.stringify(['Avambracci a terra, gomiti sotto le spalle','Corpo in linea retta dalla testa ai talloni','Contrai glutei e addominali','Mantieni la posizione per il tempo stabilito']),
    mistakesEn: JSON.stringify(['Hips sagging or raised','Holding breath','Head down or looking up']),
    mistakesIt: JSON.stringify(['Fianchi che cedono o si alzano','Trattenere il respiro','Testa abbassata o che guarda in alto']),
    tipsEn: JSON.stringify(['RKC plank (harder): squeeze everything','Progress: weighted vest, feet on bench','2min+ is a solid target']),
    tipsIt: JSON.stringify(['Plank RKC (più difficile): contrai tutto','Progressione: gilet zavorrato, piedi sulla panca','2min+ è un buon obiettivo']),
    breathingEn: 'Controlled breathing throughout.',
    breathingIt: 'Respiro controllato per tutto il movimento.',
    alternatives: JSON.stringify(['ab-wheel', 'dead-bug', 'hollow-body']),
    tags: JSON.stringify(['core','abs','isometric','bodyweight']),
  },
  {
    id: 'crunch', slug: 'crunch',
    nameEn: 'Crunch', nameIt: 'Crunch Addominali',
    descriptionEn: 'Classic spinal flexion exercise for rectus abdominis development.',
    descriptionIt: 'Classico esercizio di flessione spinale per lo sviluppo del retto addominale.',
    primaryMuscles: JSON.stringify(['abs']),
    secondaryMuscles: JSON.stringify([]),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Lie on back, knees bent, feet flat','Hands behind head or crossed at chest','Lift shoulder blades off floor','Exhale and crunch up','Lower with control']),
    instructionsIt: JSON.stringify(['Sdraiati sulla schiena, ginocchia piegate, piedi piatti','Mani dietro la testa o incrociate al petto','Alza le scapole dal pavimento','Espira e fai il crunch','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Pulling head with hands','Using hip flexors too much','Full sit-up movement']),
    mistakesIt: JSON.stringify(['Tirare la testa con le mani','Usare troppo i flessori dell\'anca','Movimento di sit-up completo']),
    tipsEn: JSON.stringify(['Think about "crunching" the rib toward pelvis','Short range = all abs','Cable crunches allow progressive loading']),
    tipsIt: JSON.stringify(['Pensa a "piegare" le costole verso il bacino','Range breve = tutti addominali','I crunch ai cavi permettono carico progressivo']),
    breathingEn: 'Exhale on crunch, inhale on return.',
    breathingIt: 'Espira nel crunch, inspira nel ritorno.',
    alternatives: JSON.stringify(['cable-crunch', 'leg-raise', 'ab-wheel']),
    tags: JSON.stringify(['isolation','abs','bodyweight','core']),
  },
  {
    id: 'leg-raise', slug: 'leg-raise',
    nameEn: 'Hanging Leg Raise', nameIt: 'Leg Raise alla Sbarra',
    descriptionEn: 'Hanging core exercise targeting lower abs and hip flexors. High difficulty.',
    descriptionIt: 'Esercizio per il core in sospensione che bersaglia gli addominali bassi e i flessori dell\'anca.',
    primaryMuscles: JSON.stringify(['abs']),
    secondaryMuscles: JSON.stringify(['hip_flexors', 'obliques']),
    equipmentId: 'pullup_bar', difficulty: 'intermediate', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Hang from pull-up bar','Raise legs to 90° or higher','Control descent','Do not swing']),
    instructionsIt: JSON.stringify(['Appenditi alla sbarra','Alza le gambe a 90° o oltre','Controlla la discesa','Non oscillare']),
    mistakesEn: JSON.stringify(['Swinging body for momentum','Partial range','Not controlling eccentric']),
    mistakesIt: JSON.stringify(['Oscillare il corpo per slancio','Range parziale','Non controllare l\'eccentrico']),
    tipsEn: JSON.stringify(['Posterior pelvic tilt to target abs more','Easier version: floor leg raises','Weighted: hold dumbbell between feet']),
    tipsIt: JSON.stringify(['Retroversione del bacino per colpire di più gli addominali','Versione più facile: leg raise a terra','Zavorrato: tieni un manubrio tra i piedi']),
    breathingEn: 'Exhale on raise, inhale on lower.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['plank', 'ab-wheel', 'crunch']),
    tags: JSON.stringify(['core','abs','bodyweight','intermediate']),
  },
  {
    id: 'ab-wheel', slug: 'ab-wheel',
    nameEn: 'Ab Wheel Rollout', nameIt: 'Ruota per Addominali',
    descriptionEn: 'Anti-extension core exercise using an ab wheel. Extremely effective for core strength.',
    descriptionIt: 'Esercizio anti-estensione per il core con la ruota addominale. Estremamente efficace per la forza del core.',
    primaryMuscles: JSON.stringify(['abs']),
    secondaryMuscles: JSON.stringify(['obliques', 'lower_back', 'lats', 'triceps']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Kneel, hold wheel with both hands','Roll forward, hips and back flat','Extend as far as possible','Pull back using core, not arms']),
    instructionsIt: JSON.stringify(['Inginocchiati, tieni la ruota con entrambe le mani','Rotola in avanti, fianchi e schiena piatti','Estendi il più possibile','Torna indietro usando il core, non le braccia']),
    mistakesEn: JSON.stringify(['Hips sagging (low back extension)','Using arms to return','Going beyond current capability']),
    mistakesIt: JSON.stringify(['Fianchi che cedono (estensione lombare)','Usare le braccia per tornare','Andare oltre le capacità attuali']),
    tipsEn: JSON.stringify(['Start with partial rollouts','From feet is hardest variation','RKC plank first as prerequisite']),
    tipsIt: JSON.stringify(['Inizia con rollout parziali','Dalla posizione eretta è la variante più difficile','Prima il plank RKC come prerequisito']),
    breathingEn: 'Inhale on roll out, exhale on pull back.',
    breathingIt: 'Inspira nel rollout, espira nel ritorno.',
    alternatives: JSON.stringify(['plank', 'dead-bug', 'cable-crunch']),
    tags: JSON.stringify(['core','abs','anti-extension','intermediate']),
  },
  {
    id: 'cable-crunch', slug: 'cable-crunch',
    nameEn: 'Cable Crunch', nameIt: 'Crunch ai Cavi',
    descriptionEn: 'Kneeling cable crunch with progressive overload. Best weighted ab exercise.',
    descriptionIt: 'Crunch ai cavi in ginocchio con sovraccarico progressivo. Il miglior esercizio addominale zavorrato.',
    primaryMuscles: JSON.stringify(['abs']),
    secondaryMuscles: JSON.stringify(['obliques']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Kneel at cable machine with rope attachment','Hold rope at either side of head','Crunch down, elbows toward knees','Full range of motion','Slowly return to upright']),
    instructionsIt: JSON.stringify(['Inginocchiati alla macchina con corda','Tieni la corda su entrambi i lati della testa','Fletti verso il basso, gomiti verso le ginocchia','Ampiezza completa del movimento','Torna lentamente in posizione eretta']),
    mistakesEn: JSON.stringify(['Hip flexion instead of spinal flexion','Pulling with arms','Not reaching full flexion']),
    mistakesIt: JSON.stringify(['Flessione dell\'anca invece di flessione spinale','Tirare con le braccia','Non raggiungere la piena flessione']),
    tipsEn: JSON.stringify(['Allows progressive overload on abs','Think about touching elbows to knees','Medium to high reps (12-15)']),
    tipsIt: JSON.stringify(['Permette il sovraccarico progressivo sugli addominali','Pensa a toccare i gomiti con le ginocchia','Rep medie-alte (12-15)']),
    breathingEn: 'Exhale on crunch, inhale on return.',
    breathingIt: 'Espira nel crunch, inspira nel ritorno.',
    alternatives: JSON.stringify(['crunch', 'ab-wheel', 'machine-crunch']),
    tags: JSON.stringify(['isolation','abs','cable','weighted']),
  },
  {
    id: 'russian-twist', slug: 'russian-twist',
    nameEn: 'Russian Twist', nameIt: 'Russian Twist',
    descriptionEn: 'Seated rotational exercise targeting obliques. Add weight for progression.',
    descriptionIt: 'Esercizio di rotazione seduto che bersaglia gli obliqui. Aggiungi peso per la progressione.',
    primaryMuscles: JSON.stringify(['obliques']),
    secondaryMuscles: JSON.stringify(['abs']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Sit with knees bent, lean back ~45°','Hold weight or clasp hands','Rotate torso side to side','Touch floor beside each hip']),
    instructionsIt: JSON.stringify(['Siediti con le ginocchia piegate, inclina indietro ~45°','Tieni un peso o unisci le mani','Ruota il busto da un lato all\'altro','Tocca il pavimento accanto a ogni fianco']),
    mistakesEn: JSON.stringify(['Moving arms without rotating spine','Feet on floor (easier) vs elevated (harder)','Not maintaining abdominal tension']),
    mistakesIt: JSON.stringify(['Spostare le braccia senza ruotare la colonna','Piedi a terra (più facile) vs elevati (più difficile)','Non mantenere la tensione addominale']),
    tipsEn: JSON.stringify(['Feet elevated makes it harder','Hold dumbbell or medicine ball for load','Control the rotation speed']),
    tipsIt: JSON.stringify(['I piedi elevati lo rendono più difficile','Tieni un manubrio o una palla medica per il carico','Controlla la velocità di rotazione']),
    breathingEn: 'Breathe rhythmically with each rotation.',
    breathingIt: 'Respira in modo ritmico ad ogni rotazione.',
    alternatives: JSON.stringify(['wood-chop', 'cable-rotation', 'pallof-press']),
    tags: JSON.stringify(['isolation','obliques','rotation','core']),
  },
  {
    id: 'mountain-climber', slug: 'mountain-climber',
    nameEn: 'Mountain Climber', nameIt: 'Mountain Climber',
    descriptionEn: 'Dynamic plank variation combining core stability with cardiovascular conditioning.',
    descriptionIt: 'Variante dinamica del plank che combina stabilità del core con condizionamento cardiovascolare.',
    primaryMuscles: JSON.stringify(['abs', 'obliques']),
    secondaryMuscles: JSON.stringify(['hip_flexors', 'front_delts', 'quads']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Start in plank/push-up position','Bring one knee toward chest','Alternate legs rapidly','Maintain plank body position']),
    instructionsIt: JSON.stringify(['Inizia in posizione di plank/piegamento','Porta un ginocchio verso il petto','Alterna le gambe rapidamente','Mantieni la posizione del plank']),
    mistakesEn: JSON.stringify(['Hips rising up','Arms bending','Loss of neutral spine']),
    mistakesIt: JSON.stringify(['Fianchi che si alzano','Braccia che si piegano','Perdita della colonna neutra']),
    tipsEn: JSON.stringify(['Slow for core focus, fast for cardio','Diagonal version hits obliques more','Great HIIT exercise']),
    tipsIt: JSON.stringify(['Lento per focus sul core, veloce per cardio','La versione diagonale colpisce più gli obliqui','Ottimo esercizio HIIT']),
    breathingEn: 'Rhythmic breathing throughout.',
    breathingIt: 'Respiro ritmico per tutto il movimento.',
    alternatives: JSON.stringify(['plank', 'burpee', 'high-knees']),
    tags: JSON.stringify(['core','cardio','bodyweight','dynamic']),
  },
  {
    id: 'pallof-press', slug: 'pallof-press',
    nameEn: 'Pallof Press', nameIt: 'Pallof Press',
    descriptionEn: 'Anti-rotation core exercise using cable. Trains rotational stability essential for all sports.',
    descriptionIt: 'Esercizio anti-rotazione per il core ai cavi. Allena la stabilità rotazionale essenziale per tutti gli sport.',
    primaryMuscles: JSON.stringify(['abs', 'obliques']),
    secondaryMuscles: JSON.stringify(['lower_back', 'glutes']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'rotation',
    instructionsEn: JSON.stringify(['Set cable at chest height','Stand side-on to machine, grab handle','Hold at chest, brace core','Press out to full arm extension','Hold 1-2s, return to chest']),
    instructionsIt: JSON.stringify(['Imposta il cavo all\'altezza del petto','Stai di fianco alla macchina, prendi il manubrio','Tieni al petto, core in tensione','Spingi fino all\'estensione completa delle braccia','Tieni 1-2s, torna al petto']),
    mistakesEn: JSON.stringify(['Rotating toward cable','Moving feet too wide','Going too heavy']),
    mistakesIt: JSON.stringify(['Ruotare verso il cavo','Piedi troppo larghi','Troppo carico']),
    tipsEn: JSON.stringify(['Resist rotation is the key','Great for spinal stability','Also effective as anti-lateral flexion variation']),
    tipsIt: JSON.stringify(['Resistere alla rotazione è la chiave','Ottimo per la stabilità spinale','Efficace anche come variante anti-flessione laterale']),
    breathingEn: 'Exhale on press, inhale on return.',
    breathingIt: 'Espira nella spinta, inspira nel ritorno.',
    alternatives: JSON.stringify(['plank', 'ab-wheel', 'cable-rotation']),
    tags: JSON.stringify(['core','anti-rotation','cable','functional']),
  },
]
