import type { NewExercise } from './types'

export const coreExercises2: NewExercise[] = [
  {
    id: 'hanging-leg-raise', slug: 'hanging-leg-raise', nameEn: 'Hanging Leg Raise', nameIt: 'Alzate gambe alle parallele',
    primaryMuscles: JSON.stringify(['lower-abs']), secondaryMuscles: JSON.stringify(['hip-flexors']),
    equipmentId: 'pull-up-bar', difficulty: 'intermediate', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Hang from pull-up bar with full extension', 'Keep legs together, core tight', 'Raise legs to 90° (parallel to floor)', 'Lower with control']),
    instructionsIt: JSON.stringify(['Appeso alla sbarra a estensione completa', 'Gambe unite, core contratto', 'Alza le gambe a 90° (parallele al suolo)', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Swinging body for momentum', 'Not controlling the lowering', 'Incomplete range of motion']),
    mistakesIt: JSON.stringify(['Dondolarsi per slancio', 'Non controllare la discesa', 'ROM incompleto']),
    tipsEn: JSON.stringify(['For beginners: bent knees first', 'Tilt pelvis back to fully engage lower abs', 'Can progress to toes-to-bar']),
    tipsIt: JSON.stringify(['Per principianti: inizia con ginocchia piegate', 'Inclina il bacino per attivare gli addominali inferiori', 'Puoi progredire alle dita ai piedi']),
    alternatives: JSON.stringify(['lying-leg-raise', 'ab-rollout']),
    tags: JSON.stringify(['abs', 'lower-abs', 'bodyweight']),
  },
  {
    id: 'cable-crunch', slug: 'cable-crunch', nameEn: 'Cable Crunch', nameIt: 'Crunch al cavo',
    primaryMuscles: JSON.stringify(['abs']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Kneel facing cable machine with rope', 'Hold rope at sides of head', 'Crunch down, flexing spine', 'Return to starting position under control']),
    instructionsIt: JSON.stringify(['Inginocchiati davanti al cavo con la corda', 'Tieni la corda ai lati della testa', 'Fai crunch, fletti la spina', 'Ritorna lentamente']),
    mistakesEn: JSON.stringify(['Pulling with arms instead of abs', 'Hip flexor dominance (hips moving)', 'Too much weight']),
    mistakesIt: JSON.stringify(['Tirare con le braccia invece degli addominali', 'Dominanza degli hip flexor', 'Troppo peso']),
    tipsEn: JSON.stringify(['Focus on spinal flexion not hip flexion', 'Look down as you crunch', 'Loaded abs respond well to progressive overload']),
    tipsIt: JSON.stringify(['Concentrati sulla flessione della spina, non dei fianchi', 'Guarda in basso durante il crunch', 'Gli addominali sotto carico rispondono bene al sovraccarico']),
    alternatives: JSON.stringify(['crunches', 'decline-crunch']),
    tags: JSON.stringify(['abs', 'cable', 'isolation']),
  },
  {
    id: 'side-plank', slug: 'side-plank', nameEn: 'Side Plank', nameIt: 'Plank laterale',
    primaryMuscles: JSON.stringify(['obliques']), secondaryMuscles: JSON.stringify(['abs', 'glutes']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie on side, prop up on forearm', 'Stack feet or stagger for stability', 'Lift hips to form straight line', 'Hold position for time']),
    instructionsIt: JSON.stringify(['Sdraiati di lato, appoggiati sull\'avambraccio', 'Piedi sovrapposti o scalati', 'Solleva i fianchi a formare linea retta', 'Mantieni la posizione per tempo']),
    mistakesEn: JSON.stringify(['Hips dropping or rising', 'Neck out of alignment', 'Breathing stopped']),
    mistakesIt: JSON.stringify(['Fianchi che scendono o salgono', 'Collo fuori allineamento', 'Apnea']),
    tipsEn: JSON.stringify(['Progress by adding arm raises or leg raises', 'Also targets shoulder stability', 'Star side plank is advanced variation']),
    tipsIt: JSON.stringify(['Progredisci aggiungendo alzate del braccio o della gamba', 'Allena anche la stabilità della spalla', 'Il side plank a stella è variante avanzata']),
    alternatives: JSON.stringify(['plank', 'oblique-crunch']),
    tags: JSON.stringify(['obliques', 'isometric', 'bodyweight']),
  },
  {
    id: 'hollow-body-hold', slug: 'hollow-body-hold', nameEn: 'Hollow Body Hold', nameIt: 'Hollow Body',
    primaryMuscles: JSON.stringify(['abs']), secondaryMuscles: JSON.stringify(['hip-flexors']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie on back, press lower back to floor', 'Raise arms overhead and legs a few inches', 'Hold the curved position', 'Breathe throughout']),
    instructionsIt: JSON.stringify(['Sdraiati, premi la zona lombare al suolo', 'Alza le braccia e le gambe di pochi centimetri', 'Mantieni la posizione curva', 'Respira']),
    mistakesEn: JSON.stringify(['Lower back arching off floor', 'Holding breath', 'Legs too high (too easy)']),
    mistakesIt: JSON.stringify(['Zona lombare che si alza dal suolo', 'Apnea', 'Gambe troppo alte (troppo facile)']),
    tipsEn: JSON.stringify(['Foundation of gymnastics core strength', 'Lower arms = harder', 'Rock for added challenge (hollow body rock)']),
    tipsIt: JSON.stringify(['Base della forza core nella ginnastica', 'Braccia più basse = più difficile', 'Dondola per difficoltà aggiuntiva']),
    alternatives: JSON.stringify(['plank', 'dead-bug']),
    tags: JSON.stringify(['abs', 'isometric', 'bodyweight']),
  },
  {
    id: 'v-up', slug: 'v-up', nameEn: 'V-Up', nameIt: 'V-Up',
    primaryMuscles: JSON.stringify(['abs']), secondaryMuscles: JSON.stringify(['hip-flexors']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie flat, arms overhead and legs straight', 'Simultaneously raise arms and legs', 'Touch toes at the top to form V shape', 'Lower with control']),
    instructionsIt: JSON.stringify(['Sdraiati piatto, braccia in su e gambe tese', 'Alza simultaneamente braccia e gambe', 'Tocca le punte dei piedi formando una V', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Bending knees', 'Only reaching halfway', 'Slamming back down']),
    mistakesIt: JSON.stringify(['Piegare le ginocchia', 'Arrivare solo a metà', 'Schiantarsi giù']),
    tipsEn: JSON.stringify(['Full range of motion is key', 'Exhale on the way up', 'Progression from crunches']),
    tipsIt: JSON.stringify(['Il ROM completo è fondamentale', 'Espira salendo', 'Progressione rispetto al crunch']),
    alternatives: JSON.stringify(['crunches', 'hanging-leg-raise']),
    tags: JSON.stringify(['abs', 'bodyweight']),
  },
  {
    id: 'pallof-press', slug: 'pallof-press', nameEn: 'Pallof Press', nameIt: 'Pallof Press',
    primaryMuscles: JSON.stringify(['obliques', 'abs']), secondaryMuscles: JSON.stringify(['glutes']),
    equipmentId: 'cable', difficulty: 'intermediate', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cable at chest height, stand perpendicular', 'Hold handle at chest with both hands', 'Press out and hold briefly', 'Return to chest']),
    instructionsIt: JSON.stringify(['Imposta il cavo all\'altezza del petto, stai perpendicolare', 'Tieni la maniglia al petto con entrambe le mani', 'Spingi avanti e tieni brevemente', 'Ritorna al petto']),
    mistakesEn: JSON.stringify(['Rotating toward cable', 'Holding breath', 'Arms not fully extended']),
    mistakesIt: JSON.stringify(['Ruotarsi verso il cavo', 'Apnea', 'Braccia non completamente tese']),
    tipsEn: JSON.stringify(['Anti-rotation core exercise', 'Keep hips square throughout', 'Great rehab and sports performance exercise']),
    tipsIt: JSON.stringify(['Esercizio di anti-rotazione del core', 'Mantieni i fianchi quadrati', 'Ottimo per riabilitazione e performance sportiva']),
    alternatives: JSON.stringify(['plank', 'side-plank']),
    tags: JSON.stringify(['obliques', 'cable', 'anti-rotation']),
  },
  {
    id: 'dragon-flag', slug: 'dragon-flag', nameEn: 'Dragon Flag', nameIt: 'Dragon Flag',
    primaryMuscles: JSON.stringify(['abs']), secondaryMuscles: JSON.stringify(['lower-back', 'hip-flexors']),
    equipmentId: 'bodyweight', difficulty: 'advanced', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie on bench, grip behind head for support', 'Raise entire body to vertical', 'Lower body in straight line (only upper back on bench)', 'Stop just before touching down and repeat']),
    instructionsIt: JSON.stringify(['Sdraiati sulla panca, tieniti dietro la testa', 'Alza l\'intero corpo in verticale', 'Abbassa il corpo in linea retta (solo la schiena alta sulla panca)', 'Fermati prima di toccare e ripeti']),
    mistakesEn: JSON.stringify(['Hips sagging', 'Not controlling the descent', 'Bending at hips']),
    mistakesIt: JSON.stringify(['Fianchi che cedono', 'Non controllare la discesa', 'Piegarsi ai fianchi']),
    tipsEn: JSON.stringify(['Made famous by Bruce Lee and Rocky', 'Progress through negatives first', 'Requires very strong core base']),
    tipsIt: JSON.stringify(['Reso famoso da Bruce Lee e Rocky', 'Progredisci prima con i negativi', 'Richiede una base di core molto forte']),
    alternatives: JSON.stringify(['hanging-leg-raise', 'hollow-body-hold']),
    tags: JSON.stringify(['abs', 'advanced', 'bodyweight']),
  },
  {
    id: 'woodchop', slug: 'woodchop', nameEn: 'Cable Woodchop', nameIt: 'Woodchop al cavo',
    primaryMuscles: JSON.stringify(['obliques']), secondaryMuscles: JSON.stringify(['abs', 'shoulders']),
    equipmentId: 'cable', difficulty: 'intermediate', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cable high, stand perpendicular', 'Grab handle with both hands', 'Pull cable diagonally down across body', 'Rotate torso through movement']),
    instructionsIt: JSON.stringify(['Imposta il cavo in alto, stai perpendicolare', 'Afferra la maniglia con entrambe le mani', 'Tira il cavo diagonalmente attraverso il corpo', 'Ruota il busto nel movimento']),
    mistakesEn: JSON.stringify(['Moving arms without rotating trunk', 'Moving too fast', 'Knee bending inconsistently']),
    mistakesIt: JSON.stringify(['Muovere le braccia senza ruotare il busto', 'Muoversi troppo veloce', 'Ginocchia che variano']),
    tipsEn: JSON.stringify(['Also do low-to-high for complete oblique work', 'Functional sport movement', 'Keep arms relatively straight']),
    tipsIt: JSON.stringify(['Fai anche la versione basso-alto per gli obliqui completi', 'Movimento sportivo funzionale', 'Mantieni le braccia relativamente tese']),
    alternatives: JSON.stringify(['side-plank', 'oblique-crunch']),
    tags: JSON.stringify(['obliques', 'cable', 'rotational']),
  },
  {
    id: 'dead-bug', slug: 'dead-bug', nameEn: 'Dead Bug', nameIt: 'Dead Bug',
    primaryMuscles: JSON.stringify(['abs']), secondaryMuscles: JSON.stringify(['hip-flexors']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie on back, arms up, knees bent at 90°', 'Press lower back into floor', 'Extend opposite arm and leg simultaneously', 'Return and repeat other side']),
    instructionsIt: JSON.stringify(['Sdraiati, braccia in su, ginocchia a 90°', 'Premi la zona lombare al suolo', 'Estendi braccio e gamba opposti simultaneamente', 'Ritorna e ripeti dall\'altro lato']),
    mistakesEn: JSON.stringify(['Lower back lifting off floor', 'Moving same side arm and leg', 'Rushing the movement']),
    mistakesIt: JSON.stringify(['Zona lombare che si alza', 'Muovere braccio e gamba dello stesso lato', 'Affrettare il movimento']),
    tipsEn: JSON.stringify(['Perfect rehab and beginner exercise', 'Great for lower back pain prevention', 'Can add resistance with cable or dumbbell']),
    tipsIt: JSON.stringify(['Perfetto per riabilitazione e principianti', 'Ottimo per prevenire il mal di schiena', 'Si può aggiungere resistenza con cavo o manubrio']),
    alternatives: JSON.stringify(['plank', 'hollow-body-hold']),
    tags: JSON.stringify(['abs', 'bodyweight', 'rehab']),
  },
  {
    id: 'russian-twist', slug: 'russian-twist', nameEn: 'Russian Twist', nameIt: 'Russian Twist',
    primaryMuscles: JSON.stringify(['obliques']), secondaryMuscles: JSON.stringify(['abs']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Sit on floor, lean back slightly, feet raised', 'Hold hands together or hold weight', 'Rotate torso to each side', 'Touch floor (or weight) beside hip each side']),
    instructionsIt: JSON.stringify(['Siediti sul pavimento, inclinati leggermente, piedi sollevati', 'Mani unite o tieni un peso', 'Ruota il busto da un lato all\'altro', 'Tocca il pavimento (o peso) a fianco del fianco']),
    mistakesEn: JSON.stringify(['Feet on floor (too easy)', 'Only moving arms without trunk rotation', 'Spine rounded excessively']),
    mistakesIt: JSON.stringify(['Piedi a terra (troppo facile)', 'Muovere solo le braccia senza rotazione del busto', 'Colonna troppo arrotondata']),
    tipsEn: JSON.stringify(['Can add weight plate or medicine ball', 'Focus on rotating from core not arms', 'Cross feet for added stability']),
    tipsIt: JSON.stringify(['Si può aggiungere disco o palla medica', 'Concentrati sulla rotazione dal core non dalle braccia', 'Incrocia i piedi per più stabilità']),
    alternatives: JSON.stringify(['woodchop', 'oblique-crunch']),
    tags: JSON.stringify(['obliques', 'bodyweight', 'rotational']),
  },
]
