import type { NewExercise } from './types'

export const SHOULDER_EXERCISES: NewExercise[] = [
  {
    id: 'overhead-press', slug: 'overhead-press',
    nameEn: 'Barbell Overhead Press', nameIt: 'Lento Avanti con Bilanciere',
    descriptionEn: 'The foundational vertical push. Builds shoulder mass, strength and overhead stability.',
    descriptionIt: 'La spinta verticale fondamentale. Costruisce massa, forza e stabilità overhead delle spalle.',
    primaryMuscles: JSON.stringify(['front_delts', 'side_delts']),
    secondaryMuscles: JSON.stringify(['triceps', 'upper_chest', 'traps']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Grip bar just outside shoulder width','Bar at upper chest/collarbone','Press straight up, head moves back then forward','Lock out overhead','Lower with control']),
    instructionsIt: JSON.stringify(['Presa appena fuori la larghezza delle spalle','Bilanciere al petto alto/clavicola','Spingi dritto in alto, la testa si sposta indietro poi avanti','Estensione completa overhead','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Pressing in front of head','Excessive lower back arch','Elbows flaring forward at start','Not locking out']),
    mistakesIt: JSON.stringify(['Spingere davanti alla testa','Eccessivo arco lombare','Gomiti che ruotano in avanti all\'inizio','Non estendere completamente']),
    tipsEn: JSON.stringify(['Squeeze glutes to protect lower back','Elbows slightly in front at bottom','Wrists straight, not cocked back','Push yourself under bar, not bar up']),
    tipsIt: JSON.stringify(['Contrai i glutei per proteggere la schiena bassa','Gomiti leggermente davanti in basso','Polsi dritti, non piegati indietro','Spingiti sotto la barra, non la barra in su']),
    breathingEn: 'Exhale on press, inhale on descent.',
    breathingIt: 'Espira nella spinta, inspira nella discesa.',
    alternatives: JSON.stringify(['dumbbell-shoulder-press', 'arnold-press', 'machine-shoulder-press']),
    tags: JSON.stringify(['compound','shoulders','push','strength','overhead']),
  },
  {
    id: 'dumbbell-shoulder-press', slug: 'dumbbell-shoulder-press',
    nameEn: 'Dumbbell Shoulder Press', nameIt: 'Lento Avanti con Manubri',
    descriptionEn: 'Seated or standing overhead press with dumbbells. Greater range of motion and unilateral correction.',
    descriptionIt: 'Pressa verticale seduta o in piedi con manubri. Maggiore range di movimento e correzione degli squilibri.',
    primaryMuscles: JSON.stringify(['front_delts', 'side_delts']),
    secondaryMuscles: JSON.stringify(['triceps', 'upper_chest']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Sit on bench with back support','Hold dumbbells at shoulder height','Press up and slightly inward at top','Lower to ear level','Repeat']),
    instructionsIt: JSON.stringify(['Siediti su panca con supporto per la schiena','Tieni i manubri all\'altezza delle spalle','Spingi in alto e leggermente verso l\'interno in cima','Abbassa al livello delle orecchie','Ripeti']),
    mistakesEn: JSON.stringify(['Arching back excessively','Not reaching full extension','Going too heavy, losing form']),
    mistakesIt: JSON.stringify(['Inarcare eccessivamente la schiena','Non raggiungere l\'estensione completa','Troppo carico, perdere la forma']),
    tipsEn: JSON.stringify(['Neutral grip (palms facing each other) reduces shoulder stress','Controlled eccentric','Can be done standing for more core activation']),
    tipsIt: JSON.stringify(['Presa neutra (palmi rivolti l\'uno all\'altro) riduce lo stress sulle spalle','Eccentrico controllato','Può essere eseguito in piedi per maggiore attivazione del core']),
    breathingEn: 'Exhale on press, inhale on descent.',
    breathingIt: 'Espira nella spinta, inspira nella discesa.',
    alternatives: JSON.stringify(['overhead-press', 'arnold-press', 'machine-shoulder-press']),
    tags: JSON.stringify(['compound','shoulders','push','dumbbell']),
  },
  {
    id: 'lateral-raise', slug: 'lateral-raise',
    nameEn: 'Lateral Raise', nameIt: 'Alzate Laterali',
    descriptionEn: 'The primary isolation exercise for side deltoids. Essential for shoulder width.',
    descriptionIt: 'Il principale esercizio di isolamento per i deltoidi laterali. Essenziale per la larghezza delle spalle.',
    primaryMuscles: JSON.stringify(['side_delts']),
    secondaryMuscles: JSON.stringify(['front_delts', 'traps']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Stand with dumbbells at sides','Slight elbow bend','Raise arms to shoulder height (T position)','Lead with elbows, not hands','Lower with control (3-4s)']),
    instructionsIt: JSON.stringify(['Stai in piedi con i manubri ai fianchi','Leggera flessione del gomito','Alza le braccia all\'altezza delle spalle (posizione a T)','Guida con i gomiti, non con le mani','Abbassa con controllo (3-4s)']),
    mistakesEn: JSON.stringify(['Swinging/using momentum','Going too heavy','Raising above shoulder height','Shrugging traps']),
    mistakesIt: JSON.stringify(['Oscillare/usare slancio','Troppo carico','Alzare sopra l\'altezza delle spalle','Alzare i trapezi']),
    tipsEn: JSON.stringify(['Slight forward lean helps target lateral head','Pinky slightly up (internal rotation of the humerus)','Cable version provides more consistent tension','High reps (15-20) work well']),
    tipsIt: JSON.stringify(['Leggera inclinazione in avanti aiuta a colpire la testa laterale','Mignolo leggermente in su (rotazione interna dell\'omero)','La versione ai cavi fornisce tensione più costante','Rep alte (15-20) funzionano bene']),
    breathingEn: 'Exhale on raise, inhale on lower.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['cable-lateral-raise', 'machine-lateral-raise', 'upright-row']),
    tags: JSON.stringify(['isolation','side-delts','shoulders','hypertrophy']),
  },
  {
    id: 'front-raise', slug: 'front-raise',
    nameEn: 'Front Raise', nameIt: 'Alzate Frontali',
    descriptionEn: 'Targets the anterior (front) deltoid head. Often done with dumbbells or plate.',
    descriptionIt: 'Bersaglia il capo anteriore del deltoide. Spesso eseguito con manubri o disco.',
    primaryMuscles: JSON.stringify(['front_delts']),
    secondaryMuscles: JSON.stringify(['upper_chest', 'side_delts']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Stand with dumbbells in front of thighs','Raise one or both arms to shoulder height','Keep arm(s) straight (slight elbow bend)','Lower with control']),
    instructionsIt: JSON.stringify(['Stai in piedi con i manubri davanti alle cosce','Alza uno o entrambi le braccia all\'altezza delle spalle','Mantieni i bracci dritti (leggera flessione del gomito)','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Going above shoulder height','Using momentum','Leaning back']),
    mistakesIt: JSON.stringify(['Andare sopra l\'altezza delle spalle','Usare slancio','Inclinarsi indietro']),
    tipsEn: JSON.stringify(['Front delts are usually overdeveloped vs rear','Often unnecessary if pressing is adequate','Alternating arms allows heavier loads']),
    tipsIt: JSON.stringify(['I deltoidi anteriori sono solitamente già ben sviluppati','Spesso non necessari se la spinta è adeguata','Alternare le braccia permette carichi più pesanti']),
    breathingEn: 'Exhale on raise, inhale on lower.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['overhead-press', 'cable-front-raise', 'plate-front-raise']),
    tags: JSON.stringify(['isolation','front-delts','shoulders']),
  },
  {
    id: 'arnold-press', slug: 'arnold-press',
    nameEn: 'Arnold Press', nameIt: 'Arnold Press',
    descriptionEn: 'Rotating dumbbell press created by Arnold Schwarzenegger. Hits all three deltoid heads.',
    descriptionIt: 'Pressa con rotazione dei manubri creata da Arnold Schwarzenegger. Colpisce tutte e tre le teste dei deltoidi.',
    primaryMuscles: JSON.stringify(['front_delts', 'side_delts']),
    secondaryMuscles: JSON.stringify(['rear_delts', 'triceps']),
    equipmentId: 'dumbbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Start with dumbbells at chin, palms facing you','Rotate outward as you press up','Finish with palms facing forward at top','Reverse rotation on way down']),
    instructionsIt: JSON.stringify(['Inizia con i manubri al mento, palmi verso di te','Ruota verso l\'esterno mentre spingi in alto','Finisci con i palmi in avanti in cima','Rotazione inversa in discesa']),
    mistakesEn: JSON.stringify(['Moving too fast through rotation','Going too heavy','Losing core stability']),
    mistakesIt: JSON.stringify(['Muoversi troppo velocemente nella rotazione','Troppo carico','Perdere stabilità del core']),
    tipsEn: JSON.stringify(['Slow controlled rotation','Seated for stability','Great for complete shoulder development']),
    tipsIt: JSON.stringify(['Rotazione lenta e controllata','Seduto per stabilità','Ottimo per sviluppo completo delle spalle']),
    breathingEn: 'Exhale on press, inhale on descent.',
    breathingIt: 'Espira nella spinta, inspira nella discesa.',
    alternatives: JSON.stringify(['dumbbell-shoulder-press', 'overhead-press', 'machine-shoulder-press']),
    tags: JSON.stringify(['compound','shoulders','push','dumbbell']),
  },
  {
    id: 'upright-row', slug: 'upright-row',
    nameEn: 'Upright Row', nameIt: 'Tirata al Mento',
    descriptionEn: 'Vertical pull that targets side delts and upper traps. Use moderate grip width.',
    descriptionIt: 'Trazione verticale che bersaglia i deltoidi laterali e i trapezi alti. Usa una larghezza di presa moderata.',
    primaryMuscles: JSON.stringify(['side_delts', 'traps']),
    secondaryMuscles: JSON.stringify(['front_delts', 'biceps']),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hold bar with shoulder-width overhand grip','Pull bar straight up along body to chin level','Lead with elbows','Lower with control']),
    instructionsIt: JSON.stringify(['Tieni la barra con presa prona alla larghezza delle spalle','Tira la barra dritto in alto lungo il corpo fino al mento','Guida con i gomiti','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Narrow grip (shoulder impingement risk)','Raising too high','Not controlling descent']),
    mistakesIt: JSON.stringify(['Presa troppo stretta (rischio impingement delle spalle)','Alzare troppo','Non controllare la discesa']),
    tipsEn: JSON.stringify(['Wider grip reduces impingement risk','Cable version preferred for shoulder health','Can also use dumbbells']),
    tipsIt: JSON.stringify(['Presa più larga riduce il rischio di impingement','La versione ai cavi è preferita per la salute delle spalle','Può essere eseguita anche con manubri']),
    breathingEn: 'Exhale on pull, inhale on descent.',
    breathingIt: 'Espira nella trazione, inspira nella discesa.',
    alternatives: JSON.stringify(['lateral-raise', 'cable-lateral-raise', 'dumbbell-shoulder-press']),
    tags: JSON.stringify(['compound','shoulders','traps','pull']),
  },
  {
    id: 'reverse-fly', slug: 'reverse-fly',
    nameEn: 'Reverse Fly', nameIt: 'Alzate Posteriori',
    descriptionEn: 'Targets rear deltoids and rhomboids. Critical for shoulder balance and posture.',
    descriptionIt: 'Bersaglia i deltoidi posteriori e i romboidi. Fondamentale per l\'equilibrio delle spalle e la postura.',
    primaryMuscles: JSON.stringify(['rear_delts']),
    secondaryMuscles: JSON.stringify(['upper_back', 'traps']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Hinge forward ~90°','Arms hanging down, slight elbow bend','Raise arms out to sides to shoulder height','Squeeze rear delts at top','Lower with control']),
    instructionsIt: JSON.stringify(['Inclina in avanti ~90°','Braccia che pendono giù, leggera flessione del gomito','Alza le braccia ai lati all\'altezza delle spalle','Contrai i deltoidi posteriori in alto','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Too much weight/momentum','Not bending over enough','Raising arms above shoulder level']),
    mistakesIt: JSON.stringify(['Troppo peso/slancio','Non inclinarsi abbastanza','Alzare le braccia sopra l\'altezza delle spalle']),
    tipsEn: JSON.stringify(['Light weight, strict form','Pec-deck (reverse) also works','High rep ranges (15-20+) effective']),
    tipsIt: JSON.stringify(['Peso leggero, forma rigorosa','Anche il pec-deck in reverse funziona','Rep alte (15-20+) efficaci']),
    breathingEn: 'Exhale on raise, inhale on lower.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['face-pull', 'cable-rear-delt-fly', 'band-pull-apart']),
    tags: JSON.stringify(['isolation','rear-delts','shoulder-health','posture']),
  },
  {
    id: 'shrug', slug: 'shrug',
    nameEn: 'Barbell Shrug', nameIt: 'Scrollate con Bilanciere',
    descriptionEn: 'Primary trap isolation exercise. Builds the upper trapezius for a thick, powerful look.',
    descriptionIt: 'Principale esercizio di isolamento per i trapezi. Sviluppa i trapezi superiori per un aspetto spesso e potente.',
    primaryMuscles: JSON.stringify(['traps']),
    secondaryMuscles: JSON.stringify(['rear_delts', 'forearms']),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Hold barbell in front with overhand grip','Shrug shoulders straight up','Hold at top 1-2s','Lower with control']),
    instructionsIt: JSON.stringify(['Tieni il bilanciere davanti con presa prona','Alza le spalle dritto in su','Tieni in alto 1-2s','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Rolling shoulders (injury risk)','Not reaching full contraction','Jerky movement']),
    mistakesIt: JSON.stringify(['Ruotare le spalle (rischio infortuni)','Non raggiungere la piena contrazione','Movimento brusco']),
    tipsEn: JSON.stringify(['Straight up and down only','Straps allow heavier loads','Dumbbell shrugs allow more rotation']),
    tipsIt: JSON.stringify(['Solo su e giù','Le fascette permettono carichi più pesanti','Le scrollate con manubri permettono più rotazione']),
    breathingEn: 'Exhale on shrug up, inhale on lower.',
    breathingIt: 'Espira nell\'alzata, inspira nella discesa.',
    alternatives: JSON.stringify(['dumbbell-shrug', 'cable-shrug', 'trap-bar-shrug']),
    tags: JSON.stringify(['isolation','traps','barbell']),
  },
  {
    id: 'cable-lateral-raise', slug: 'cable-lateral-raise',
    nameEn: 'Cable Lateral Raise', nameIt: 'Alzate Laterali ai Cavi',
    descriptionEn: 'Cable version of lateral raise with constant tension throughout the range of motion.',
    descriptionIt: 'Versione ai cavi dell\'alzata laterale con tensione costante per tutto il range di movimento.',
    primaryMuscles: JSON.stringify(['side_delts']),
    secondaryMuscles: JSON.stringify(['traps']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cable at lowest position','Stand beside machine, grab handle with far hand','Raise arm out to shoulder height','Slight elbow bend throughout','Control descent']),
    instructionsIt: JSON.stringify(['Imposta il cavo alla posizione più bassa','Stai di fianco alla macchina, prendi il manubrio con la mano lontana','Alza il braccio all\'altezza delle spalle','Leggera flessione del gomito per tutto il movimento','Controlla la discesa']),
    mistakesEn: JSON.stringify(['Using momentum','Going above shoulder height','Torso leaning away']),
    mistakesIt: JSON.stringify(['Usare slancio','Andare sopra l\'altezza delle spalle','Busto che si inclina']),
    tipsEn: JSON.stringify(['Better tension at bottom vs dumbbells','Cross-body cable adds variety','High reps work well']),
    tipsIt: JSON.stringify(['Migliore tensione in basso rispetto ai manubri','Il cavo incrociato aggiunge varietà','Rep alte funzionano bene']),
    breathingEn: 'Exhale on raise, inhale on lower.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['lateral-raise', 'machine-lateral-raise']),
    tags: JSON.stringify(['isolation','side-delts','cable']),
  },
]
