import type { NewExercise } from './types'

export const shouldersExercises2: NewExercise[] = [
  {
    id: 'cable-face-pull', slug: 'cable-face-pull', nameEn: 'Cable Face Pull', nameIt: 'Face pull al cavo',
    primaryMuscles: JSON.stringify(['rear-delts']), secondaryMuscles: JSON.stringify(['upper-back', 'rotator-cuff']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'pull',
    instructionsEn: JSON.stringify(['Set cable at eye level with rope attachment', 'Grab rope with overhand grip', 'Pull rope to face, elbows flaring out', 'Squeeze rear delts at peak']),
    instructionsIt: JSON.stringify(['Imposta il cavo all\'altezza degli occhi con corda', 'Afferra la corda in presa prona', 'Tira la corda verso il viso, gomiti alti', 'Stringi i deltoidi posteriori al picco']),
    mistakesEn: JSON.stringify(['Cable too low', 'Using too much weight', 'Not flaring elbows enough']),
    mistakesIt: JSON.stringify(['Cavo troppo basso', 'Troppo peso', 'Gomiti non abbastanza alti']),
    tipsEn: JSON.stringify(['Key exercise for shoulder health', 'Do higher reps (15-20+)', 'Great for posture correction']),
    tipsIt: JSON.stringify(['Esercizio chiave per la salute delle spalle', 'Fai ripetizioni alte (15-20+)', 'Ottimo per la correzione posturale']),
    alternatives: JSON.stringify(['face-pull', 'reverse-fly']),
    tags: JSON.stringify(['rear-delts', 'cable', 'shoulder-health']),
  },
  {
    id: 'plate-front-raise', slug: 'plate-front-raise', nameEn: 'Plate Front Raise', nameIt: 'Alzata frontale con disco',
    primaryMuscles: JSON.stringify(['front-delts']), secondaryMuscles: JSON.stringify(['upper-chest']),
    equipmentId: 'barbell', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Hold weight plate with both hands at 3 and 9 o\'clock', 'Stand with slight forward lean', 'Raise plate to eye level', 'Lower with control']),
    instructionsIt: JSON.stringify(['Tieni il disco con entrambe le mani alle 3 e 9', 'Stai con leggera inclinazione avanti', 'Alza il disco all\'altezza degli occhi', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Using momentum', 'Going above eye level', 'Not controlling descent']),
    mistakesIt: JSON.stringify(['Usare lo slancio', 'Alzare oltre l\'altezza degli occhi', 'Non controllare la discesa']),
    tipsEn: JSON.stringify(['Neutral grip is easier on shoulder joint', 'Great variation from dumbbell front raise']),
    tipsIt: JSON.stringify(['La presa neutra è migliore per l\'articolazione', 'Ottima variante rispetto all\'alzata frontale con manubrio']),
    alternatives: JSON.stringify(['front-raise', 'overhead-press']),
    tags: JSON.stringify(['shoulders', 'front-delts', 'isolation']),
  },
  {
    id: 'push-press', slug: 'push-press', nameEn: 'Push Press', nameIt: 'Push Press',
    primaryMuscles: JSON.stringify(['shoulders']), secondaryMuscles: JSON.stringify(['triceps', 'quads']),
    equipmentId: 'barbell', difficulty: 'advanced', movementType: 'push',
    instructionsEn: JSON.stringify(['Bar at shoulder level', 'Slight knee dip (quarter squat)', 'Explosively drive hips to press bar overhead', 'Lock out arms at top', 'Lower with control']),
    instructionsIt: JSON.stringify(['Bilanciere all\'altezza delle spalle', 'Leggera flessione delle ginocchia', 'Spingi esplosivamente i fianchi per pressare sopra la testa', 'Braccia tese in alto', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Too large knee dip', 'Pressing before leg drive', 'Letting bar drift forward']),
    mistakesIt: JSON.stringify(['Troppa flessione delle ginocchia', 'Pressare prima della spinta delle gambe', 'Il bilanciere scivola avanti']),
    tipsEn: JSON.stringify(['Allows heavier loads than strict press', 'Develops explosive pressing power', 'Part of Olympic lifting']),
    tipsIt: JSON.stringify(['Permette carichi più pesanti dello strict press', 'Sviluppa potenza esplosiva', 'Parte del sollevamento olimpico']),
    alternatives: JSON.stringify(['overhead-press', 'dumbbell-shoulder-press']),
    tags: JSON.stringify(['shoulders', 'explosive', 'barbell', 'compound']),
  },
  {
    id: 'behind-neck-press', slug: 'behind-neck-press', nameEn: 'Behind-the-Neck Press', nameIt: 'Press dietro la nuca',
    primaryMuscles: JSON.stringify(['shoulders']), secondaryMuscles: JSON.stringify(['triceps']),
    equipmentId: 'barbell', difficulty: 'advanced', movementType: 'push',
    instructionsEn: JSON.stringify(['Bar behind neck at shoulder level', 'Wide grip, elbows flared', 'Press upward until arms extended', 'Lower to starting position']),
    instructionsIt: JSON.stringify(['Bilanciere dietro la nuca', 'Presa larga, gomiti alti', 'Pressa verso l\'alto fino a braccia tese', 'Abbassa alla posizione iniziale']),
    mistakesEn: JSON.stringify(['Doing this with poor shoulder mobility', 'Bar path too far back', 'Heavy weight before mastering technique']),
    mistakesIt: JSON.stringify(['Farlo con mobilità scapolare scarsa', 'Traiettoria del bilanciere troppo indietro', 'Peso pesante prima di padroneggiare la tecnica']),
    tipsEn: JSON.stringify(['Requires good shoulder mobility', 'Use lighter weight than front press', 'Skip if any shoulder pain']),
    tipsIt: JSON.stringify(['Richiede buona mobilità delle spalle', 'Usa meno peso rispetto al press frontale', 'Salta se c\'è dolore alle spalle']),
    alternatives: JSON.stringify(['overhead-press', 'arnold-press']),
    tags: JSON.stringify(['shoulders', 'barbell', 'advanced']),
  },
]
