import type { NewExercise } from './types'

export const cardioExercises2: NewExercise[] = [
  {
    id: 'rowing-machine', slug: 'rowing-machine', nameEn: 'Rowing Machine', nameIt: 'Vogatore',
    primaryMuscles: JSON.stringify(['back', 'legs']), secondaryMuscles: JSON.stringify(['biceps', 'core']),
    equipmentId: 'machine', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Sit on seat, feet strapped in', 'Drive legs first, then lean back slightly', 'Pull handle to lower chest', 'Extend arms, lean forward, then bend knees']),
    instructionsIt: JSON.stringify(['Siediti, piedi agganciati', 'Spingi prima con le gambe, poi inclina leggermente', 'Porta la maniglia al petto basso', 'Estendi le braccia, inclina avanti, poi piega le ginocchia']),
    mistakesEn: JSON.stringify(['Pulling with arms before legs drive', 'Hunching forward', 'Too much lean back']),
    mistakesIt: JSON.stringify(['Tirare con le braccia prima della spinta delle gambe', 'Gobbire', 'Troppa inclinazione indietro']),
    tipsEn: JSON.stringify(['Power ratio: 60% legs, 20% core, 20% arms', 'Full body conditioning exercise', 'Great for low-impact cardio']),
    tipsIt: JSON.stringify(['Rapporto potenza: 60% gambe, 20% core, 20% braccia', 'Esercizio di condizionamento total body', 'Ottimo per cardio a basso impatto']),
    alternatives: JSON.stringify(['cycling', 'jump-rope']),
    tags: JSON.stringify(['cardio', 'machine', 'full-body']),
  },
  {
    id: 'stair-climber', slug: 'stair-climber', nameEn: 'Stair Climber', nameIt: 'Scalatore di scale',
    primaryMuscles: JSON.stringify(['glutes', 'quads']), secondaryMuscles: JSON.stringify(['calves', 'hamstrings']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Set machine to desired level', 'Step onto pedals', 'Maintain upright posture, slight lean forward', 'Continuous stepping motion']),
    instructionsIt: JSON.stringify(['Imposta la macchina al livello desiderato', 'Sali sui pedali', 'Postura eretta, lieve inclinazione avanti', 'Movimento continuo di scalata']),
    mistakesEn: JSON.stringify(['Leaning heavily on handrails', 'Using very low step depth', 'Looking down at feet']),
    mistakesIt: JSON.stringify(['Appoggiarsi fortemente ai corrimano', 'Usare profondità del passo molto bassa', 'Guardare i piedi']),
    tipsEn: JSON.stringify(['Avoid holding rails for better calorie burn', 'Steep incline activates glutes more', 'Low impact on joints compared to running']),
    tipsIt: JSON.stringify(['Evita di tenerti ai corrimano per più calorie', 'Inclinazione ripida attiva di più i glutei', 'Basso impatto sulle articolazioni rispetto alla corsa']),
    alternatives: JSON.stringify(['treadmill', 'cycling']),
    tags: JSON.stringify(['cardio', 'machine', 'low-impact']),
  },
  {
    id: 'battle-ropes', slug: 'battle-ropes', nameEn: 'Battle Ropes', nameIt: 'Battle Ropes',
    primaryMuscles: JSON.stringify(['shoulders', 'core']), secondaryMuscles: JSON.stringify(['arms', 'back']),
    equipmentId: 'cable', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Hold one rope in each hand', 'Alternate raising and slamming each rope', 'Maintain slight knee bend', 'Keep core tight throughout']),
    instructionsIt: JSON.stringify(['Tieni una corda in ogni mano', 'Alza e abbassa alternando le corde', 'Mantieni leggera flessione delle ginocchia', 'Core contratto']),
    mistakesEn: JSON.stringify(['Standing too upright', 'Only using arms without core', 'Stopping between waves']),
    mistakesIt: JSON.stringify(['Stare troppo eretti', 'Usare solo le braccia senza il core', 'Fermarsi tra le onde']),
    tipsEn: JSON.stringify(['Excellent for conditioning and fat loss', 'Try different patterns: waves, circles, slams', 'Great finisher after strength training']),
    tipsIt: JSON.stringify(['Eccellente per condizionamento e perdita di grasso', 'Prova diversi pattern: onde, cerchi, slam', 'Ottimo finisher dopo l\'allenamento di forza']),
    alternatives: JSON.stringify(['rowing-machine', 'jump-rope']),
    tags: JSON.stringify(['cardio', 'conditioning', 'full-body']),
  },
  {
    id: 'sled-push', slug: 'sled-push', nameEn: 'Sled Push', nameIt: 'Spinta del Sled',
    primaryMuscles: JSON.stringify(['quads', 'glutes']), secondaryMuscles: JSON.stringify(['calves', 'core', 'shoulders']),
    equipmentId: 'machine', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Load sled with desired weight', 'Lean forward and grip handles', 'Drive forward with powerful leg pushes', 'Maintain forward lean throughout']),
    instructionsIt: JSON.stringify(['Carica il sled con il peso desiderato', 'Inclinati avanti, impugna i manici', 'Spingi avanti con potenti spinte delle gambe', 'Mantieni l\'inclinazione avanti']),
    mistakesEn: JSON.stringify(['Too upright posture', 'Short choppy steps', 'Not using full hip extension']),
    mistakesIt: JSON.stringify(['Postura troppo eretta', 'Passi corti e irregolari', 'Non usare l\'estensione completa dell\'anca']),
    tipsEn: JSON.stringify(['Sprint or slow heavy push for different effects', 'Zero eccentric so great for recovery days', 'Builds leg drive and conditioning simultaneously']),
    tipsIt: JSON.stringify(['Sprint o spinta lenta pesante per effetti diversi', 'Zero eccentrica quindi ottimo nei giorni di recupero', 'Costruisce la spinta delle gambe e il condizionamento']),
    alternatives: JSON.stringify(['sprint', 'cycling']),
    tags: JSON.stringify(['cardio', 'conditioning', 'legs']),
  },
  {
    id: 'box-jump', slug: 'box-jump', nameEn: 'Box Jump', nameIt: 'Salto sulla box',
    primaryMuscles: JSON.stringify(['quads', 'glutes']), secondaryMuscles: JSON.stringify(['calves', 'core']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Stand in front of box, feet shoulder-width', 'Swing arms back, bend knees into quick dip', 'Explode up, pull knees to chest', 'Land softly with bent knees on box']),
    instructionsIt: JSON.stringify(['Stai davanti alla box, piedi larghezza spalle', 'Porta le braccia indietro, piegati velocemente', 'Esplodi in alto, porta le ginocchia al petto', 'Atterra morbidamente con ginocchia piegate']),
    mistakesEn: JSON.stringify(['Landing with straight legs', 'Box too high (dive-bombing)', 'Not fully extending at takeoff']),
    mistakesIt: JSON.stringify(['Atterrare con gambe tese', 'Box troppo alta', 'Non estendersi completamente al decollo']),
    tipsEn: JSON.stringify(['Step down rather than jumping down (saves joints)', 'Start with lower box, increase gradually', 'Focus on soft landing mechanics']),
    tipsIt: JSON.stringify(['Scendi con un passo invece di saltare giù', 'Inizia con box più bassa', 'Concentrati sugli atterraggi morbidi']),
    alternatives: JSON.stringify(['jump-squat', 'burpees']),
    tags: JSON.stringify(['cardio', 'plyometric', 'bodyweight']),
  },
  {
    id: 'mountain-climber', slug: 'mountain-climber', nameEn: 'Mountain Climber', nameIt: 'Scalatore',
    primaryMuscles: JSON.stringify(['core', 'hip-flexors']), secondaryMuscles: JSON.stringify(['shoulders', 'quads']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Start in push-up position', 'Drive one knee toward chest', 'Quickly switch, bringing other knee in', 'Maintain plank position throughout']),
    instructionsIt: JSON.stringify(['Inizia in posizione di flessione', 'Porta un ginocchio verso il petto', 'Cambia rapidamente, porta l\'altro ginocchio', 'Mantieni la posizione di plank']),
    mistakesEn: JSON.stringify(['Hips rising too high', 'Not bringing knee far enough', 'Slow pace defeats the purpose']),
    mistakesIt: JSON.stringify(['Fianchi che salgono troppo', 'Ginocchio che non arriva abbastanza', 'Ritmo lento sconferisce lo scopo']),
    tipsEn: JSON.stringify(['Keep hips level with shoulders', 'Speed is key for cardio benefit', 'Can slow it down for core focus']),
    tipsIt: JSON.stringify(['Mantieni i fianchi allo stesso livello delle spalle', 'La velocità è fondamentale per il beneficio cardiovascolare', 'Si può rallentare per focus sul core']),
    alternatives: JSON.stringify(['burpees', 'high-knees']),
    tags: JSON.stringify(['cardio', 'bodyweight', 'core']),
  },
  {
    id: 'assault-bike', slug: 'assault-bike', nameEn: 'Assault Bike (Air Bike)', nameIt: 'Assault Bike',
    primaryMuscles: JSON.stringify(['legs', 'shoulders']), secondaryMuscles: JSON.stringify(['core', 'arms']),
    equipmentId: 'machine', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Sit on seat, feet on pedals', 'Grip handles with arms extended', 'Simultaneously pedal and push/pull handles', 'Maintain consistent pace or intervals']),
    instructionsIt: JSON.stringify(['Siediti, piedi sui pedali', 'Impugna i manici a braccia estese', 'Pedala e spingi/tira i manici simultaneamente', 'Mantieni ritmo costante o fai intervalli']),
    mistakesEn: JSON.stringify(['Only using legs or only using arms', 'Slouching posture', 'Going all-out immediately (saves nothing)']),
    mistakesIt: JSON.stringify(['Usare solo gambe o solo braccia', 'Postura sciatta', 'Andare al massimo subito']),
    tipsEn: JSON.stringify(['The harder you push the harder the resistance', 'Perfect for HIIT protocols', 'Full body cardio with minimal impact']),
    tipsIt: JSON.stringify(['Più spingi più è resistente', 'Perfetto per protocolli HIIT', 'Cardio total body con impatto minimo']),
    alternatives: JSON.stringify(['rowing-machine', 'cycling']),
    tags: JSON.stringify(['cardio', 'machine', 'HIIT', 'full-body']),
  },
  {
    id: 'sprint', slug: 'sprint', nameEn: 'Sprint', nameIt: 'Scatto',
    primaryMuscles: JSON.stringify(['quads', 'hamstrings', 'glutes']), secondaryMuscles: JSON.stringify(['calves', 'core']),
    equipmentId: 'bodyweight', difficulty: 'intermediate', movementType: 'cardio',
    instructionsEn: JSON.stringify(['Start from athletic stance', 'Explosive start with powerful arm drive', 'High knee lift, pawing action with feet', 'Maintain forward lean and full effort']),
    instructionsIt: JSON.stringify(['Inizia da postura atletica', 'Partenza esplosiva con forza delle braccia', 'Ginocchia alte, azione di "graffio"', 'Mantieni inclinazione avanti e massimo sforzo']),
    mistakesEn: JSON.stringify(['Overstriding', 'Poor arm mechanics', 'Tensing up shoulders and neck']),
    mistakesIt: JSON.stringify(['Passi troppo lunghi', 'Meccanica delle braccia scadente', 'Irrigidire spalle e collo']),
    tipsEn: JSON.stringify(['10-30 second sprints with full recovery', 'Can do hill sprints for extra resistance', 'Most effective fat-burning cardio']),
    tipsIt: JSON.stringify(['Sprint da 10-30 secondi con recupero completo', 'Si possono fare sprint in salita', 'Il cardio più efficace per bruciare grassi']),
    alternatives: JSON.stringify(['jump-rope', 'cycling']),
    tags: JSON.stringify(['cardio', 'bodyweight', 'HIIT', 'outdoor']),
  },
]
