import type { NewExercise } from './types'

export const LEG_EXERCISES: NewExercise[] = [
  {
    id: 'barbell-squat', slug: 'barbell-squat',
    nameEn: 'Barbell Back Squat', nameIt: 'Squat con Bilanciere',
    descriptionEn: 'The king of leg exercises. High-bar or low-bar back squat for total leg and core development.',
    descriptionIt: 'Il re degli esercizi per le gambe. Squat con bilanciere in alto o basso per lo sviluppo totale delle gambe e del core.',
    primaryMuscles: JSON.stringify(['quads', 'glutes']),
    secondaryMuscles: JSON.stringify(['hamstrings', 'lower_back', 'abs']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'squat',
    instructionsEn: JSON.stringify(['Bar on upper traps (high-bar) or rear delts (low-bar)','Feet shoulder-width, toes slightly out','Break at hips and knees simultaneously','Descend until thighs parallel or below','Drive through full foot to stand']),
    instructionsIt: JSON.stringify(['Bilanciere sui trapezi alti (high-bar) o deltoidi posteriori (low-bar)','Piedi alla larghezza delle spalle, punte leggermente fuori','Rompi alle anche e alle ginocchia simultaneamente','Scendi finché le cosce sono parallele o sotto','Spingi attraverso tutto il piede per alzarti']),
    mistakesEn: JSON.stringify(['Knees caving inward','Rounding lower back at bottom','Heels rising off floor','Forward lean (excessive)']),
    mistakesIt: JSON.stringify(['Ginocchia che cedono verso l\'interno','Curvare la schiena bassa in fondo','Talloni che si alzano dal pavimento','Inclinazione in avanti (eccessiva)']),
    tipsEn: JSON.stringify(['Brace 360° before descent','Knees track over toes','Core tight throughout','Full depth if mobility allows']),
    tipsIt: JSON.stringify(['Tensione 360° prima della discesa','Le ginocchia seguono i piedi','Core sempre in tensione','Profondità completa se la mobilità lo permette']),
    breathingEn: 'Big breath and brace before descent, exhale at top.',
    breathingIt: 'Grande respiro e tensione prima della discesa, espira in cima.',
    alternatives: JSON.stringify(['goblet-squat', 'leg-press', 'front-squat']),
    tags: JSON.stringify(['compound','quads','glutes','squat','strength']),
  },
  {
    id: 'front-squat', slug: 'front-squat',
    nameEn: 'Front Squat', nameIt: 'Squat Frontale',
    descriptionEn: 'Barbell in front rack position. Quad-dominant with upright torso and core challenge.',
    descriptionIt: 'Bilanciere in posizione anteriore. Dominante sui quadricipiti con busto eretto e sfida al core.',
    primaryMuscles: JSON.stringify(['quads']),
    secondaryMuscles: JSON.stringify(['glutes', 'abs', 'upper_back']),
    equipmentId: 'barbell', difficulty: 'advanced', movementType: 'squat',
    instructionsEn: JSON.stringify(['Bar in front rack or cross-arm position','Elbows high, torso very upright','Squat deep keeping torso vertical','Drive up through heels']),
    instructionsIt: JSON.stringify(['Bilanciere in posizione anteriore o a braccia incrociate','Gomiti alti, busto molto eretto','Squat profondo mantenendo il busto verticale','Spingi in su attraverso i talloni']),
    mistakesEn: JSON.stringify(['Elbows dropping','Torso folding forward','Insufficient wrist/shoulder mobility']),
    mistakesIt: JSON.stringify(['Gomiti che cadono','Busto che si piega in avanti','Mobilità insufficiente di polsi/spalle']),
    tipsEn: JSON.stringify(['Wrist and shoulder mobility prerequisite','More quad emphasis than back squat','Great for improving back squat technique']),
    tipsIt: JSON.stringify(['Mobilità di polsi e spalle prerequisita','Più enfasi sui quadricipiti rispetto allo squat con bilanciere','Ottimo per migliorare la tecnica dello squat']),
    breathingEn: 'Brace before descent, exhale at top.',
    breathingIt: 'Tensione prima della discesa, espira in cima.',
    alternatives: JSON.stringify(['barbell-squat', 'goblet-squat', 'hack-squat']),
    tags: JSON.stringify(['compound','quads','squat','advanced']),
  },
  {
    id: 'goblet-squat', slug: 'goblet-squat',
    nameEn: 'Goblet Squat', nameIt: 'Goblet Squat',
    descriptionEn: 'Counterbalanced squat holding weight at chest. Perfect form developer and quad builder.',
    descriptionIt: 'Squat controbilanciato tenendo il peso al petto. Perfetto per sviluppare la forma e costruire i quadricipiti.',
    primaryMuscles: JSON.stringify(['quads', 'glutes']),
    secondaryMuscles: JSON.stringify(['abs', 'upper_back']),
    equipmentId: 'kettlebell', difficulty: 'beginner', movementType: 'squat',
    instructionsEn: JSON.stringify(['Hold kettlebell/dumbbell at chest','Feet shoulder-width, toes out 30°','Squat deep, elbows inside knees','Keep chest up throughout','Drive up to stand']),
    instructionsIt: JSON.stringify(['Tieni kettlebell/manubrio al petto','Piedi alla larghezza delle spalle, punte a 30°','Squat profondo, gomiti dentro le ginocchia','Mantieni il petto alto per tutto il movimento','Spingi in su per alzarti']),
    mistakesEn: JSON.stringify(['Heels lifting','Chest falling forward','Knees caving in']),
    mistakesIt: JSON.stringify(['Talloni che si alzano','Petto che cade in avanti','Ginocchia che cedono']),
    tipsEn: JSON.stringify(['Great for learning squat pattern','Weight acts as counterbalance','Good mobility exercise too']),
    tipsIt: JSON.stringify(['Ottimo per imparare il pattern dello squat','Il peso fa da controbilanciamento','Ottimo anche come esercizio di mobilità']),
    breathingEn: 'Inhale on descent, exhale on rise.',
    breathingIt: 'Inspira in discesa, espira in salita.',
    alternatives: JSON.stringify(['barbell-squat', 'leg-press', 'hack-squat']),
    tags: JSON.stringify(['compound','quads','beginner','squat','kettlebell']),
  },
  {
    id: 'leg-press', slug: 'leg-press',
    nameEn: 'Leg Press', nameIt: 'Pressa per Gambe',
    descriptionEn: 'Machine compound leg exercise. Great for loading quads and glutes without lower back strain.',
    descriptionIt: 'Esercizio composto per le gambe alla macchina. Ottimo per caricare quadricipiti e glutei senza stress sulla schiena bassa.',
    primaryMuscles: JSON.stringify(['quads', 'glutes']),
    secondaryMuscles: JSON.stringify(['hamstrings']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'squat',
    instructionsEn: JSON.stringify(['Set seat, feet shoulder-width on platform','Unlock safety handles','Lower platform until 90° knee angle','Press platform away to full extension','Do not lock out knees']),
    instructionsIt: JSON.stringify(['Imposta il sedile, piedi alla larghezza delle spalle sulla piattaforma','Sblocca le maniglie di sicurezza','Abbassa la piattaforma fino a 90° di angolo del ginocchio','Spingi la piattaforma lontano fino alla completa estensione','Non bloccare le ginocchia']),
    mistakesEn: JSON.stringify(['Feet too low (knee stress)','Not reaching depth','Locking knees at top','Lower back lifting off pad']),
    mistakesIt: JSON.stringify(['Piedi troppo in basso (stress ginocchio)','Non raggiungere la profondità','Bloccare le ginocchia in cima','Schiena bassa che si stacca dal cuscinetto']),
    tipsEn: JSON.stringify(['Higher feet = more glutes and hamstrings','Lower feet = more quad emphasis','Great for high volume work']),
    tipsIt: JSON.stringify(['Piedi più in alto = più glutei e femorali','Piedi più in basso = più enfasi sui quadricipiti','Ottimo per lavoro ad alto volume']),
    breathingEn: 'Exhale on press, inhale on descent.',
    breathingIt: 'Espira nella spinta, inspira nella discesa.',
    alternatives: JSON.stringify(['barbell-squat', 'hack-squat', 'goblet-squat']),
    tags: JSON.stringify(['compound','quads','machine','legs']),
  },
  {
    id: 'lunges', slug: 'lunges',
    nameEn: 'Lunges', nameIt: 'Affondi',
    descriptionEn: 'Unilateral leg exercise for balance, strength and size. Walking, reverse or stationary.',
    descriptionIt: 'Esercizio unilaterale per le gambe per equilibrio, forza e dimensione. Camminata, inversi o stazionari.',
    primaryMuscles: JSON.stringify(['quads', 'glutes']),
    secondaryMuscles: JSON.stringify(['hamstrings', 'abs']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'squat',
    instructionsEn: JSON.stringify(['Stand with dumbbells at sides','Step forward, lower rear knee toward floor','Front knee above ankle','Push back to standing or continue walking']),
    instructionsIt: JSON.stringify(['In piedi con i manubri ai lati','Fai un passo in avanti, abbassa il ginocchio posteriore verso il pavimento','Ginocchio anteriore sopra la caviglia','Spingiti indietro in posizione eretta o continua a camminare']),
    mistakesEn: JSON.stringify(['Knee going past toes','Torso leaning forward excessively','Unstable front foot']),
    mistakesIt: JSON.stringify(['Ginocchio che supera le punte dei piedi','Busto che si inclina in avanti eccessivamente','Piede anteriore instabile']),
    tipsEn: JSON.stringify(['Step length determines emphasis','Long step = more glute','Short step = more quad']),
    tipsIt: JSON.stringify(['La lunghezza del passo determina l\'enfasi','Passo lungo = più glutei','Passo corto = più quadricipiti']),
    breathingEn: 'Inhale on descent, exhale on return.',
    breathingIt: 'Inspira in discesa, espira nel ritorno.',
    alternatives: JSON.stringify(['barbell-squat', 'split-squat', 'step-up']),
    tags: JSON.stringify(['compound','quads','glutes','unilateral','lunge']),
  },
  {
    id: 'bulgarian-split-squat', slug: 'bulgarian-split-squat',
    nameEn: 'Bulgarian Split Squat', nameIt: 'Split Squat Bulgaro',
    descriptionEn: 'Single-leg squat with rear foot elevated. Excellent for quad and glute hypertrophy.',
    descriptionIt: 'Squat monopodalico con piede posteriore elevato. Eccellente per l\'ipertrofia di quadricipiti e glutei.',
    primaryMuscles: JSON.stringify(['quads', 'glutes']),
    secondaryMuscles: JSON.stringify(['hamstrings', 'abs']),
    equipmentId: 'dumbbell', difficulty: 'intermediate', movementType: 'squat',
    instructionsEn: JSON.stringify(['Rear foot on bench, front foot forward','Lower rear knee toward floor','Keep front knee over ankle','Drive through front heel to stand']),
    instructionsIt: JSON.stringify(['Piede posteriore sulla panca, piede anteriore avanti','Abbassa il ginocchio posteriore verso il pavimento','Mantieni il ginocchio anteriore sopra la caviglia','Spingi attraverso il tallone anteriore per alzarti']),
    mistakesEn: JSON.stringify(['Front foot too close to bench','Torso collapsing forward','Rear foot placement unstable']),
    mistakesIt: JSON.stringify(['Piede anteriore troppo vicino alla panca','Busto che crolla in avanti','Posizionamento del piede posteriore instabile']),
    tipsEn: JSON.stringify(['One of the best single-leg exercises','More forward lean = more glute','More upright = more quad']),
    tipsIt: JSON.stringify(['Uno dei migliori esercizi monopodalici','Più inclinazione in avanti = più glutei','Più eretto = più quadricipiti']),
    breathingEn: 'Inhale on descent, exhale on press.',
    breathingIt: 'Inspira in discesa, espira nella spinta.',
    alternatives: JSON.stringify(['lunges', 'barbell-squat', 'step-up']),
    tags: JSON.stringify(['compound','quads','glutes','unilateral','advanced']),
  },
  {
    id: 'leg-curl', slug: 'leg-curl',
    nameEn: 'Leg Curl', nameIt: 'Leg Curl',
    descriptionEn: 'Hamstring isolation on a machine. Lying or seated variation for posterior thigh development.',
    descriptionIt: 'Isolamento dei femorali su macchina. Variante sdraiata o seduta per lo sviluppo della coscia posteriore.',
    primaryMuscles: JSON.stringify(['hamstrings']),
    secondaryMuscles: JSON.stringify(['glutes']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Lie face down (or sit) on machine','Pad positioned above ankle','Curl legs to full contraction','Squeeze hamstrings','Lower with control']),
    instructionsIt: JSON.stringify(['Sdraiati a faccia in giù (o siediti) sulla macchina','Cuscinetto posizionato sopra la caviglia','Arriccia le gambe fino alla piena contrazione','Contrai i femorali','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Hips rising off pad','Using momentum','Partial range']),
    mistakesIt: JSON.stringify(['Fianchi che si alzano dal cuscinetto','Usare slancio','Range parziale']),
    tipsEn: JSON.stringify(['Full range is key','Slow eccentric for hypertrophy','Seated version keeps more constant tension']),
    tipsIt: JSON.stringify(['Il range completo è fondamentale','Eccentrico lento per l\'ipertrofia','La versione seduta mantiene tensione più costante']),
    breathingEn: 'Exhale on curl, inhale on return.',
    breathingIt: 'Espira nel curl, inspira nel ritorno.',
    alternatives: JSON.stringify(['romanian-deadlift', 'nordic-curl', 'cable-leg-curl']),
    tags: JSON.stringify(['isolation','hamstrings','machine','legs']),
  },
  {
    id: 'leg-extension', slug: 'leg-extension',
    nameEn: 'Leg Extension', nameIt: 'Leg Extension',
    descriptionEn: 'Quad isolation exercise on a machine. Targets the rectus femoris and VMO.',
    descriptionIt: 'Esercizio di isolamento per i quadricipiti su macchina. Bersaglia il retto femorale e il VMO.',
    primaryMuscles: JSON.stringify(['quads']),
    secondaryMuscles: JSON.stringify([]),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Sit in machine, pad above ankles','Extend legs to full extension','Squeeze quads at top','Lower with control']),
    instructionsIt: JSON.stringify(['Siediti sulla macchina, cuscinetto sopra le caviglie','Estendi le gambe fino all\'estensione completa','Contrai i quadricipiti in cima','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Bouncing at top','Not reaching full extension','Using too much weight']),
    mistakesIt: JSON.stringify(['Rimbalzare in cima','Non raggiungere la piena estensione','Troppo carico']),
    tipsEn: JSON.stringify(['Some knee discomfort is common','Partial reps from 45-90° can reduce joint stress','Good finisher after squats']),
    tipsIt: JSON.stringify(['Un po\' di disagio al ginocchio è comune','Le rep parziali da 45-90° possono ridurre lo stress articolare','Buono come finisher dopo gli squat']),
    breathingEn: 'Exhale on extension, inhale on return.',
    breathingIt: 'Espira nell\'estensione, inspira nel ritorno.',
    alternatives: JSON.stringify(['barbell-squat', 'hack-squat', 'leg-press']),
    tags: JSON.stringify(['isolation','quads','machine','legs']),
  },
  {
    id: 'calf-raise', slug: 'calf-raise',
    nameEn: 'Standing Calf Raise', nameIt: 'Alzate in Punta di Piedi',
    descriptionEn: 'Primary calf isolation exercise. Targets gastrocnemius with straight leg.',
    descriptionIt: 'Principale esercizio di isolamento per i polpacci. Bersaglia il gastrocnemio con la gamba dritta.',
    primaryMuscles: JSON.stringify(['calves']),
    secondaryMuscles: JSON.stringify([]),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Stand on edge of platform, heels hanging off','Push up to full extension (toes pointing down)','Stretch at bottom, contract at top','Full range of motion']),
    instructionsIt: JSON.stringify(['In piedi sul bordo della piattaforma, talloni appesi','Spingi su fino alla piena estensione (punte in basso)','Allungamento in basso, contrazione in alto','Ampiezza completa del movimento']),
    mistakesEn: JSON.stringify(['Partial range (no stretch at bottom)','Bouncing','Too much weight with poor form']),
    mistakesIt: JSON.stringify(['Range parziale (nessun allungamento in basso)','Rimbalzare','Troppo carico con scarsa forma']),
    tipsEn: JSON.stringify(['High rep range (15-20+) for calves','Bent knee version (seated) targets soleus','Slow eccentrics key for growth']),
    tipsIt: JSON.stringify(['Range di rep alto (15-20+) per i polpacci','La versione con ginocchio piegato (seduto) bersaglia il soleo','Gli eccentrici lenti sono fondamentali per la crescita']),
    breathingEn: 'Exhale on rise, inhale on descent.',
    breathingIt: 'Espira in salita, inspira in discesa.',
    alternatives: JSON.stringify(['seated-calf-raise', 'donkey-calf-raise']),
    tags: JSON.stringify(['isolation','calves','legs']),
  },
  {
    id: 'hip-thrust', slug: 'hip-thrust',
    nameEn: 'Hip Thrust', nameIt: 'Hip Thrust',
    descriptionEn: 'Barbell glute bridge variation. The most effective exercise for glute mass.',
    descriptionIt: 'Variante del ponte glutei con bilanciere. L\'esercizio più efficace per la massa dei glutei.',
    primaryMuscles: JSON.stringify(['glutes']),
    secondaryMuscles: JSON.stringify(['hamstrings', 'quads']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Shoulders on bench, barbell across hips','Feet flat, hip-width apart','Drive hips up until body forms straight line','Squeeze glutes hard at top','Lower with control']),
    instructionsIt: JSON.stringify(['Spalle sulla panca, bilanciere sui fianchi','Piedi piatti, alla larghezza delle anche','Spingi i fianchi in alto fino a formare una linea retta','Contrai i glutei forte in alto','Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Hyperextending at the top (low back arch)','Feet too far or close','Not reaching full hip extension']),
    mistakesIt: JSON.stringify(['Iperestensione in cima (arco lombare)','Piedi troppo lontani o vicini','Non raggiungere la piena estensione dell\'anca']),
    tipsEn: JSON.stringify(['Post thrust pads for comfort','Chin tucked, eyes forward','Glute squeeze is the cue']),
    tipsIt: JSON.stringify(['Cuscinetti per comfort','Mento abbassato, occhi avanti','La contrazione dei glutei è il segnale']),
    breathingEn: 'Exhale on thrust, inhale on descent.',
    breathingIt: 'Espira nella spinta, inspira nella discesa.',
    alternatives: JSON.stringify(['glute-bridge', 'romanian-deadlift', 'cable-pull-through']),
    tags: JSON.stringify(['compound','glutes','hinge','barbell']),
  },
  {
    id: 'sumo-deadlift', slug: 'sumo-deadlift',
    nameEn: 'Sumo Deadlift', nameIt: 'Stacco Sumo',
    descriptionEn: 'Wide-stance deadlift variation. Emphasizes inner thighs and glutes, shorter range of motion.',
    descriptionIt: 'Variante dello stacco con piedi larghi. Enfatizza l\'interno coscia e i glutei, minor range di movimento.',
    primaryMuscles: JSON.stringify(['glutes', 'hamstrings']),
    secondaryMuscles: JSON.stringify(['quads', 'adductors', 'lower_back']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Wide stance, toes pointing out 45°','Grip shoulder-width inside legs','Hip hinge keeping back neutral','Drive floor away, hips and shoulders rise together','Lock out at top']),
    instructionsIt: JSON.stringify(['Posizione larga, punte a 45°','Presa alla larghezza delle spalle dentro le gambe','Hip hinge mantenendo la schiena neutra','Spingi il pavimento lontano, anche e spalle salgono insieme','Blocca in alto']),
    mistakesEn: JSON.stringify(['Knees caving','Shoulders rising before hips','Bar drifting from body']),
    mistakesIt: JSON.stringify(['Ginocchia che cedono','Spalle che salgono prima delle anche','La barra si allontana dal corpo']),
    tipsEn: JSON.stringify(['Drive knees out through entire lift','Good for those with longer torsos','More hip-dominant than conventional']),
    tipsIt: JSON.stringify(['Spingi le ginocchia fuori per tutta la sollevata','Buono per chi ha il busto lungo','Più dominante per le anche rispetto al convenzionale']),
    breathingEn: 'Valsalva maneuver: brace and hold through rep.',
    breathingIt: 'Manovra di Valsalva: tensione e trattieni durante la rep.',
    alternatives: JSON.stringify(['deadlift', 'romanian-deadlift', 'hip-thrust']),
    tags: JSON.stringify(['compound','glutes','hinge','barbell','strength']),
  },
  {
    id: 'nordic-curl', slug: 'nordic-curl',
    nameEn: 'Nordic Curl', nameIt: 'Nordic Curl',
    descriptionEn: 'Eccentric hamstring exercise with high injury prevention value. Very challenging.',
    descriptionIt: 'Esercizio eccentrico per i femorali con alto valore preventivo degli infortuni. Molto impegnativo.',
    primaryMuscles: JSON.stringify(['hamstrings']),
    secondaryMuscles: JSON.stringify(['glutes', 'lower_back']),
    equipmentId: 'bodyweight', difficulty: 'advanced', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Kneel with feet secured (partner or machine)','Slowly lower torso toward floor','Control descent as long as possible','Catch with hands at bottom','Use arms to push back to start']),
    instructionsIt: JSON.stringify(['Inginocchiati con i piedi fissati (partner o macchina)','Abbassa lentamente il busto verso il pavimento','Controlla la discesa il più a lungo possibile','Atterra con le mani in basso','Usa le braccia per tornare al punto di partenza']),
    mistakesEn: JSON.stringify(['Going too fast (no eccentric control)','Not engaging hamstrings throughout','Trying concentric before building eccentric']),
    mistakesIt: JSON.stringify(['Andare troppo veloce (nessun controllo eccentrico)','Non attivare i femorali per tutto il movimento','Tentare il concentrico prima di sviluppare l\'eccentrico']),
    tipsEn: JSON.stringify(['Eccentric only to start','Reduces hamstring injury risk by 50%+','Slow progression required']),
    tipsIt: JSON.stringify(['Solo eccentrico per iniziare','Riduce il rischio di infortuni ai femorali del 50%+','Progressione lenta richiesta']),
    breathingEn: 'Inhale on descent, exhale on return.',
    breathingIt: 'Inspira in discesa, espira nel ritorno.',
    alternatives: JSON.stringify(['leg-curl', 'romanian-deadlift', 'good-morning']),
    tags: JSON.stringify(['isolation','hamstrings','bodyweight','advanced','injury-prevention']),
  },
]
