import type { NewExercise } from './types'

export const legsExercises2: NewExercise[] = [
  {
    id: 'hack-squat', slug: 'hack-squat', nameEn: 'Hack Squat', nameIt: 'Hack Squat',
    primaryMuscles: JSON.stringify(['quads']), secondaryMuscles: JSON.stringify(['glutes']),
    equipmentId: 'machine', difficulty: 'intermediate', movementType: 'squat',
    instructionsEn: JSON.stringify(['Position shoulders under pads', 'Feet shoulder-width, toes slightly out', 'Lower until thighs parallel', 'Drive through heels to extend']),
    instructionsIt: JSON.stringify(['Posiziona le spalle sotto i pad', 'Piedi larghezza spalle, punte leggermente fuori', 'Scendi fino a coscia parallela', 'Spingi con i talloni']),
    mistakesEn: JSON.stringify(['Knees caving inward', 'Not reaching full depth', 'Rising onto toes']),
    mistakesIt: JSON.stringify(['Ginocchia che cedono all\'interno', 'Non raggiungere la profondità completa', 'Alzarsi sulle punte']),
    tipsEn: JSON.stringify(['Great quad isolator', 'Safer on lower back than barbell squat', 'Pause at bottom for more intensity']),
    tipsIt: JSON.stringify(['Ottimo isolatore dei quadricipiti', 'Più sicuro per la schiena rispetto allo squat col bilanciere', 'Pausa in basso per più intensità']),
    alternatives: JSON.stringify(['barbell-squat', 'leg-press']),
    tags: JSON.stringify(['quads', 'machine', 'squat']),
  },
  {
    id: 'step-up', slug: 'step-up', nameEn: 'Step-Up', nameIt: 'Step-up',
    primaryMuscles: JSON.stringify(['glutes', 'quads']), secondaryMuscles: JSON.stringify(['hamstrings']),
    equipmentId: 'dumbbell', difficulty: 'beginner', movementType: 'squat',
    instructionsEn: JSON.stringify(['Hold dumbbells at sides', 'Step one foot onto bench or box', 'Drive through heel to stand', 'Step back down and repeat']),
    instructionsIt: JSON.stringify(['Tieni manubri ai lati', 'Posa un piede sulla panca o box', 'Spingi con il tallone per alzarti', 'Scendi e ripeti']),
    mistakesEn: JSON.stringify(['Pushing off back foot', 'Leaning forward too much', 'Using too high a step']),
    mistakesIt: JSON.stringify(['Spingere con il piede di dietro', 'Inclinarsi troppo avanti', 'Step troppo alto']),
    tipsEn: JSON.stringify(['Great unilateral lower body exercise', 'Can be done with bodyweight for beginners']),
    tipsIt: JSON.stringify(['Ottimo esercizio unilaterale per gli arti inferiori', 'Può essere fatto a corpo libero per principianti']),
    alternatives: JSON.stringify(['lunges', 'bulgarian-split-squat']),
    tags: JSON.stringify(['glutes', 'quads', 'unilateral']),
  },
  {
    id: 'cable-kickback', slug: 'cable-kickback', nameEn: 'Cable Kickback', nameIt: 'Cable Kickback',
    primaryMuscles: JSON.stringify(['glutes']), secondaryMuscles: JSON.stringify(['hamstrings']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Attach ankle cuff to low cable', 'Face the machine, hold for support', 'Kick working leg backward', 'Squeeze glute at peak extension']),
    instructionsIt: JSON.stringify(['Attacca il cinturino alla caviglia al cavo basso', 'Guarda la macchina, tieniti', 'Calcio con la gamba all\'indietro', 'Contrai il gluteo in estensione massima']),
    mistakesEn: JSON.stringify(['Arching lower back too much', 'Using momentum', 'Not squeezing at the top']),
    mistakesIt: JSON.stringify(['Inarcare troppo la zona lombare', 'Usare lo slancio', 'Non contrarre in cima']),
    tipsEn: JSON.stringify(['Focus on glute contraction, not leg height', 'Great isolation movement for glutes']),
    tipsIt: JSON.stringify(['Concentrati sulla contrazione del gluteo, non sull\'altezza', 'Ottimo isolamento del gluteo']),
    alternatives: JSON.stringify(['hip-thrust', 'cable-kickback']),
    tags: JSON.stringify(['glutes', 'cable', 'isolation']),
  },
  {
    id: 'sissy-squat', slug: 'sissy-squat', nameEn: 'Sissy Squat', nameIt: 'Sissy Squat',
    primaryMuscles: JSON.stringify(['quads']), secondaryMuscles: JSON.stringify([]),
    equipmentId: 'bodyweight', difficulty: 'advanced', movementType: 'squat',
    instructionsEn: JSON.stringify(['Stand with feet together', 'Hold support with one hand', 'Lean back as you bend knees forward over toes', 'Lower until knee nearly touches floor', 'Return to standing']),
    instructionsIt: JSON.stringify(['Stai in piedi con i piedi uniti', 'Tieniti con una mano', 'Inclinati indietro mentre le ginocchia avanzano sulle punte', 'Scendi fino a quasi toccare il pavimento', 'Ritorna in piedi']),
    mistakesEn: JSON.stringify(['Not having enough ankle/knee flexibility', 'Going too deep too soon', 'Losing balance']),
    mistakesIt: JSON.stringify(['Mobilità insufficiente di caviglia/ginocchio', 'Scendere troppo presto', 'Perdere l\'equilibrio']),
    tipsEn: JSON.stringify(['Extreme quad isolation', 'Build up gradually - tough on knees', 'Can hold weight plate for added resistance']),
    tipsIt: JSON.stringify(['Isolamento estremo dei quadricipiti', 'Progredisci gradualmente - stressante per le ginocchia', 'Puoi tenere un disco per aumentare il carico']),
    alternatives: JSON.stringify(['leg-extension', 'hack-squat']),
    tags: JSON.stringify(['quads', 'bodyweight', 'advanced']),
  },
  {
    id: 'glute-bridge', slug: 'glute-bridge', nameEn: 'Glute Bridge', nameIt: 'Ponte glutei',
    primaryMuscles: JSON.stringify(['glutes']), secondaryMuscles: JSON.stringify(['hamstrings', 'core']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'hinge',
    instructionsEn: JSON.stringify(['Lie on back, knees bent, feet flat', 'Drive hips toward ceiling', 'Squeeze glutes at top', 'Lower with control']),
    instructionsIt: JSON.stringify(['Sdraiati, ginocchia piegate, piedi piatti', 'Spingi i fianchi verso il soffitto', 'Contrai i glutei in alto', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Not fully extending hips', 'Using lower back instead of glutes', 'Feet too far from body']),
    mistakesIt: JSON.stringify(['Non estendere completamente i fianchi', 'Usare la zona lombare invece dei glutei', 'Piedi troppo lontani dal corpo']),
    tipsEn: JSON.stringify(['Great beginner glute exercise', 'Progress to hip thrust with weight', 'Can do single-leg variation']),
    tipsIt: JSON.stringify(['Ottimo esercizio per principianti', 'Progredisci al hip thrust con peso', 'Puoi fare la variante monopedale']),
    alternatives: JSON.stringify(['hip-thrust', 'cable-kickback']),
    tags: JSON.stringify(['glutes', 'bodyweight', 'hinge']),
  },
  {
    id: 'wall-sit', slug: 'wall-sit', nameEn: 'Wall Sit', nameIt: 'Sit alla parete',
    primaryMuscles: JSON.stringify(['quads']), secondaryMuscles: JSON.stringify(['glutes', 'calves']),
    equipmentId: 'bodyweight', difficulty: 'beginner', movementType: 'squat',
    instructionsEn: JSON.stringify(['Stand against wall', 'Slide down until thighs parallel to floor', 'Hold position for time', 'Keep back flat against wall']),
    instructionsIt: JSON.stringify(['Appoggiati alla parete', 'Scivola giù fino a coscia parallela al suolo', 'Mantieni la posizione per tempo', 'Schiena piatta contro la parete']),
    mistakesEn: JSON.stringify(['Knees past toes', 'Thighs not parallel to floor', 'Pushing with arms']),
    mistakesIt: JSON.stringify(['Ginocchia oltre le punte', 'Coscia non parallela al suolo', 'Spingere con le braccia']),
    tipsEn: JSON.stringify(['Isometric quad strength builder', 'Good for rehabilitation']),
    tipsIt: JSON.stringify(['Costruisce forza isometrica dei quadricipiti', 'Buono per la riabilitazione']),
    alternatives: JSON.stringify(['leg-extension', 'barbell-squat']),
    tags: JSON.stringify(['quads', 'bodyweight', 'isometric']),
  },
]
