import type { NewExercise } from './types'

export const chestExercises2: NewExercise[] = [
  {
    id: 'cable-fly', slug: 'cable-fly', nameEn: 'Cable Fly', nameIt: 'Croci ai cavi',
    primaryMuscles: JSON.stringify(['chest']), secondaryMuscles: JSON.stringify(['shoulders']),
    equipmentId: 'cable', difficulty: 'intermediate', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cables at shoulder height', 'Grab handles with slight bend in elbows', 'Bring hands together in arc motion', 'Control the return']),
    instructionsIt: JSON.stringify(['Imposta i cavi all\'altezza delle spalle', 'Afferra le maniglie con leggera flessione dei gomiti', 'Avvicina le mani in movimento arcuato', 'Controlla il ritorno']),
    mistakesEn: JSON.stringify(['Using too much weight', 'Locking elbows', 'Not controlling the eccentric']),
    mistakesIt: JSON.stringify(['Usare troppo peso', 'Bloccare i gomiti', 'Non controllare l\'eccentrica']),
    tipsEn: JSON.stringify(['Squeeze chest at peak contraction', 'Keep slight elbow bend throughout', 'Focus on the stretch at the bottom']),
    tipsIt: JSON.stringify(['Stringi il petto nella contrazione massima', 'Mantieni leggera flessione dei gomiti', 'Concentrati sullo stretching in basso']),
    alternatives: JSON.stringify(['dumbbell-fly', 'pec-deck', 'cable-crossover']),
    tags: JSON.stringify(['chest', 'cable', 'isolation']),
  },
  {
    id: 'landmine-press', slug: 'landmine-press', nameEn: 'Landmine Press', nameIt: 'Landmine Press',
    primaryMuscles: JSON.stringify(['chest', 'shoulders']), secondaryMuscles: JSON.stringify(['triceps']),
    equipmentId: 'barbell', difficulty: 'intermediate', movementType: 'push',
    instructionsEn: JSON.stringify(['Load one end of barbell in corner or landmine attachment', 'Grip end with both hands at chest', 'Press upward and forward', 'Lower with control']),
    instructionsIt: JSON.stringify(['Carica un\'estremità del bilanciere', 'Impugna con entrambe le mani al petto', 'Spingi in alto e avanti', 'Abbassa con controllo']),
    mistakesEn: JSON.stringify(['Flaring elbows too wide', 'Losing core stability', 'Rushing the movement']),
    mistakesIt: JSON.stringify(['Gomiti troppo allargati', 'Perdere stabilità del core', 'Eseguire il movimento troppo veloce']),
    tipsEn: JSON.stringify(['Keep core tight', 'Great for shoulder-friendly chest work', 'Can be done one-arm for asymmetry correction']),
    tipsIt: JSON.stringify(['Mantieni il core contratto', 'Ottimo per chi ha problemi alle spalle', 'Può essere fatto monobraccio']),
    alternatives: JSON.stringify(['bench-press', 'dumbbell-press']),
    tags: JSON.stringify(['chest', 'shoulders', 'barbell']),
  },
  {
    id: 'low-cable-fly', slug: 'low-cable-fly', nameEn: 'Low Cable Fly', nameIt: 'Croci ai cavi bassi',
    primaryMuscles: JSON.stringify(['upper-chest']), secondaryMuscles: JSON.stringify(['shoulders']),
    equipmentId: 'cable', difficulty: 'beginner', movementType: 'isolation',
    instructionsEn: JSON.stringify(['Set cables at lowest position', 'Grab handles, lean slightly forward', 'Bring hands up and together', 'Squeeze upper chest at top']),
    instructionsIt: JSON.stringify(['Imposta i cavi in posizione bassa', 'Afferra le maniglie, inclinati leggermente', 'Porta le mani in su e insieme', 'Contrai il petto alto in cima']),
    mistakesEn: JSON.stringify(['Not leaning forward enough', 'Bending elbows too much', 'Using momentum']),
    mistakesIt: JSON.stringify(['Non inclinarsi abbastanza', 'Flettere troppo i gomiti', 'Usare lo slancio']),
    tipsEn: JSON.stringify(['Targets upper chest specifically', 'Great finisher after compound movements']),
    tipsIt: JSON.stringify(['Lavora specificamente il petto alto', 'Ottimo finisher dopo i compound']),
    alternatives: JSON.stringify(['incline-bench-press', 'cable-fly']),
    tags: JSON.stringify(['upper-chest', 'cable', 'isolation']),
  },
  {
    id: 'dumbbell-pullover', slug: 'dumbbell-pullover', nameEn: 'Dumbbell Pullover', nameIt: 'Pullover con manubrio',
    primaryMuscles: JSON.stringify(['chest']), secondaryMuscles: JSON.stringify(['back', 'triceps']),
    equipmentId: 'dumbbell', difficulty: 'intermediate', movementType: 'pull',
    instructionsEn: JSON.stringify(['Lie perpendicular on bench', 'Hold dumbbell over chest with both hands', 'Lower dumbbell in arc behind head', 'Pull back to starting position']),
    instructionsIt: JSON.stringify(['Sdraiati perpendicolarmente sulla panca', 'Tieni il manubrio sopra il petto', 'Abbassalo in arco dietro la testa', 'Riporta alla posizione iniziale']),
    mistakesEn: JSON.stringify(['Using too heavy weight', 'Bending elbows too much', 'Not controlling the range']),
    mistakesIt: JSON.stringify(['Peso eccessivo', 'Flettere troppo i gomiti', 'Non controllare il ROM']),
    tipsEn: JSON.stringify(['Works both chest and back', 'Keep slight bend in elbows', 'Deep stretch at the bottom']),
    tipsIt: JSON.stringify(['Lavora sia il petto che la schiena', 'Mantieni leggera flessione dei gomiti', 'Stretching profondo in basso']),
    alternatives: JSON.stringify(['cable-straight-arm-pulldown', 'dumbbell-fly']),
    tags: JSON.stringify(['chest', 'back', 'dumbbell']),
  },
  {
    id: 'machine-chest-press', slug: 'machine-chest-press', nameEn: 'Machine Chest Press', nameIt: 'Chest press alla macchina',
    primaryMuscles: JSON.stringify(['chest']), secondaryMuscles: JSON.stringify(['triceps', 'shoulders']),
    equipmentId: 'machine', difficulty: 'beginner', movementType: 'push',
    instructionsEn: JSON.stringify(['Adjust seat so handles are at chest level', 'Grip handles, elbows at 90°', 'Press forward until arms nearly extended', 'Return with control']),
    instructionsIt: JSON.stringify(['Regola il sedile', 'Afferra le maniglie, gomiti a 90°', 'Spingi avanti quasi a braccia tese', 'Ritorna con controllo']),
    mistakesEn: JSON.stringify(['Seat too high or low', 'Bouncing the stack', 'Not using full range of motion']),
    mistakesIt: JSON.stringify(['Sedile mal regolato', 'Non controllare il movimento', 'ROM incompleto']),
    tipsEn: JSON.stringify(['Great for beginners and finishers', 'Allows higher reps safely']),
    tipsIt: JSON.stringify(['Ottimo per principianti e finisher', 'Permette più ripetizioni in sicurezza']),
    alternatives: JSON.stringify(['bench-press', 'dumbbell-press']),
    tags: JSON.stringify(['chest', 'machine', 'push']),
  },
]
