export const MUSCLES = [
  { id: 'chest',       nameEn: 'Chest',          nameIt: 'Petto',                   group: 'upper_body', bodyPart: 'chest' },
  { id: 'upper_chest', nameEn: 'Upper Chest',     nameIt: 'Petto Alto',              group: 'upper_body', bodyPart: 'chest' },
  { id: 'lats',        nameEn: 'Lats',            nameIt: 'Dorsali',                 group: 'upper_body', bodyPart: 'back' },
  { id: 'upper_back',  nameEn: 'Upper Back',      nameIt: 'Schiena Alta',            group: 'upper_body', bodyPart: 'back' },
  { id: 'lower_back',  nameEn: 'Lower Back',      nameIt: 'Lombare',                 group: 'upper_body', bodyPart: 'back' },
  { id: 'traps',       nameEn: 'Trapezius',       nameIt: 'Trapezi',                 group: 'upper_body', bodyPart: 'back' },
  { id: 'rear_delts',  nameEn: 'Rear Delts',      nameIt: 'Deltoidi Posteriori',     group: 'upper_body', bodyPart: 'shoulders' },
  { id: 'front_delts', nameEn: 'Front Delts',     nameIt: 'Deltoidi Anteriori',      group: 'upper_body', bodyPart: 'shoulders' },
  { id: 'side_delts',  nameEn: 'Side Delts',      nameIt: 'Deltoidi Laterali',       group: 'upper_body', bodyPart: 'shoulders' },
  { id: 'biceps',      nameEn: 'Biceps',          nameIt: 'Bicipiti',                group: 'upper_body', bodyPart: 'arms' },
  { id: 'triceps',     nameEn: 'Triceps',         nameIt: 'Tricipiti',               group: 'upper_body', bodyPart: 'arms' },
  { id: 'forearms',    nameEn: 'Forearms',        nameIt: 'Avambracci',              group: 'upper_body', bodyPart: 'arms' },
  { id: 'abs',         nameEn: 'Abs',             nameIt: 'Addominali',              group: 'core',       bodyPart: 'core' },
  { id: 'obliques',    nameEn: 'Obliques',        nameIt: 'Obliqui',                 group: 'core',       bodyPart: 'core' },
  { id: 'glutes',      nameEn: 'Glutes',          nameIt: 'Glutei',                  group: 'lower_body', bodyPart: 'glutes' },
  { id: 'quads',       nameEn: 'Quadriceps',      nameIt: 'Quadricipiti',            group: 'lower_body', bodyPart: 'legs' },
  { id: 'hamstrings',  nameEn: 'Hamstrings',      nameIt: 'Femorali',                group: 'lower_body', bodyPart: 'legs' },
  { id: 'calves',      nameEn: 'Calves',          nameIt: 'Polpacci',                group: 'lower_body', bodyPart: 'legs' },
  { id: 'adductors',   nameEn: 'Adductors',       nameIt: 'Adduttori',               group: 'lower_body', bodyPart: 'legs' },
  { id: 'abductors',   nameEn: 'Abductors',       nameIt: 'Abduttori',               group: 'lower_body', bodyPart: 'legs' },
  { id: 'hip_flexors', nameEn: 'Hip Flexors',     nameIt: 'Flessori dell\'Anca',     group: 'lower_body', bodyPart: 'legs' },
  { id: 'rotator_cuff',nameEn: 'Rotator Cuff',    nameIt: 'Cuffia dei Rotatori',     group: 'upper_body', bodyPart: 'shoulders' },
]
